### ISSUE TITLE
Integrations and Expansions

### ISSUE THREAD

**Issue by jibzzjibzz** [HydroBlockchain/hcdp#10]
**What language is it in?**
Front end : angular
Back end : node express server (FeathersJs)

Using hydro app for identity management of bank's customer details and bank's users details

**Describe how to use it**
There are 2 uses cases on the EDMRMS, they are the bank and the customers.
Use case 1 will be able to : 
1. Make cheque requisition from the app
2. Use cheque for payment to existing user of EDMRMS
3. Cheque transaction records

Use case 2 will be able to : 
1.  Approve and assign digital cheque number range to customer with requisitions
2. View reports transaction (daily,weekly,monthly,quaterly etc)
3. Cheque audits (who does what and when)

**Any important links?**
None

**Ethereum Address**
0x8b052077aa9Ba59337db7099d25681404db7a98b

**Other important information**
I have worked in a software financial company for 2 years in Lagos, Nigeria where we develop enterprise applications for banks and financial instituions. The current cheque requestion and management process is quite manual and cost effective. For bank's customers, except for VIP cases, a customer would have to walk into a bank to request for cheque which costs money / booklet. For banks, it costs a fortune to pay for rent for CMC (Cheque Managment Centers), buy cheque leaves, buy encoder machines that does printing of customer details of cheque leaves and also validating the authenticity of a cheque when tendered. I strongly, it is time we digitize cheque system in Nigeria and all over the world

**Comment by AndyHydro** [comment]
This is very interesting and we would love to help you work with this more, but we are looking for finalized applications here. Why don't you hop into our dev chat on discord https://discord.gg/zYZEabW and we can help you!
