### ISSUE TITLE
[Educational Content] HYDROGEN PLATFORM — Beyond Just FINTECH, Driving Financial Inclusion

### ISSUE THREAD

**Issue by richidson999** [HydroBlockchain/hcdp#100]
**https://medium.com/@awuku.awuah/hydrogen-platform-beyond-just-fintech-driving-financial-inclusion-63801ad89499**

**0x0020a5ea9EaFD49484348481d72A1b6b31EE2d8B
[Hydrogen Ecosystem.docx](https://github.com/hydrogen-dev/hcdp/files/2018971/Hydrogen.Ecosystem.docx)
**

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
