### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by Raphyjay** [HydroBlockchain/hcdp#102]
https://youtu.be/j8IWXPgh9eM

0x6BD3DD230D56848b7b14B524084b1f3c9bD47f20

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
