### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by burhank6161** [HydroBlockchain/hcdp#103]
+**What language is it in?**
Turkish

**Link to the posted content**
https://medium.com/@brhnk61_55920/hydro-raindrop-2fa-uygulaması-482a11a4edbd

https://medium.com/@brhnk61_55920/block-tank-2018-recap-turkish-review-53a03ec8d15a

https://gate.io/listing
I pioneered the list

To tell snowflake turkish and share

https://medium.com/@brhnk61_55920/hydro-snowflake-41a6f1c668d5

Hydrogen Snowflake
Turkish language prepared by staying true to the original

https://www.youtube.com/watch?v=afzEdXvxqOc

**Ethereum Address**
0x7681Ed0Bbbcd36b55d98D911F97ccc0AD2EB2174

brhnk61@gmail.com 
https://twitter.com/brhnk61 Old account suspended @bkocabey11
https://t.me/Burhank61
https://www.facebook.com/BurhanK61
https://github.com/burhank61 ->https://www.hydrogenplatform.com/hydro Follow
https://github.com/burhank6161

**Comment by burhank6161** [comment]
![aaaaa](https://user-images.githubusercontent.com/39428864/40265738-c7fd62ec-5b46-11e8-8b9d-d71e7391ae7c.png)

**Comment by ghost** [comment]
The links are broken.

**Comment by burhank6161** [comment]
ok J'adoube

**Comment by burhank6161** [comment]
https://gate.io/listing 

I pioneered the list

**Comment by burhank6161** [comment]
To tell snowflake turkish and share

https://medium.com/@brhnk61_55920/hydro-snowflake-41a6f1c668d5

**Comment by burhank6161** [comment]
Hydrogen Snowflake
Turkish language prepared by staying true to the original

Ethereum Address
0x7681Ed0Bbbcd36b55d98D911F97ccc0AD2EB2174

https://www.youtube.com/watch?v=afzEdXvxqOc

**Comment by ghost** [comment]
We are no longer accepting content submissions as part of the HCDP. Thank you for your submission.

**Comment by burhank6161** [comment]
![23467350_2074097016144636_3971867660375861304_o](https://user-images.githubusercontent.com/39428864/41872899-f8a9594e-78cb-11e8-9c8f-08f8d7f8a04b.jpg)
