### ISSUE TITLE
Hydrogen platform -beyond just FINTECH

### ISSUE THREAD

**Issue by Holyridax** [HydroBlockchain/hcdp#106]
https://medium.com/@awuku.awuah/hydrogen-platform-beyond-just-fintech-driving-financial-inclusion-63801ad89499 

0x86E0924CBfCCbf2AC2E061DB2884a5E2f33Dcf89

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
