### ISSUE TITLE
Educational Content- HYDRO: A REVOLUTIONARY PLATFORM REDEFINING APPLICATION,DOCUMENT SECURITY,IDENTITY MANAGEMENT AMONGST OTHERS IN THE BLOCKCHAIN SPACE

### ISSUE THREAD

**Issue by Jannyh** [HydroBlockchain/hcdp#110]
https://steemit.com/ethereum/@jannyh/hydro-a-revolutionary-platform-redefining-application-document-security-identity-management-amongst-others-in-the-blockchain

Eth Address: 0x3Fc07d782e70E8Dc08328129aF2A31d0f21d6e99

**Comment by Jannyh** [comment]
Hydro has been phenomenal and I have great confidence in it's ability to affect lives,e-commerce amongst others in the global space

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
