### ISSUE TITLE
10 reasons why Hydro coin will be the greatest in the world of cryptocurrency 

### ISSUE THREAD

**Issue by Holyridax** [HydroBlockchain/hcdp#111]
https://medium.com/@aniemmanuel/reasons-why-hydrogen-platform-can-be-one-of-the-greatest-coin-in-future-576cb8403680

0x86E0924CBfCCbf2AC2E061DB2884a5E2f33Dcf89

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
