### ISSUE TITLE
Educational Content in Turkish / What is Hydrogen Platform

### ISSUE THREAD

**Issue by limonyay** [HydroBlockchain/hcdp#112]
https://steemit.com/hydro/@limonyay/hydrogen-platform
https://www.reddit.com/r/ProjectHydro/comments/8kkqwh/hydro_nedir/

0x76448273D4f34dA59383370FDAe26213Dd183dF9

**Comment by ghost** [comment]
We are no longer accepting content submissions as part of the HCDP. Thank you for your submission.

**Comment by limonyay** [comment]
So you are not going to distribute bounties? Did we write these articles
for nothing?

2018-06-11 18:54 GMT+03:00 Noah Zinsmeister <notifications@github.com>:

**Comment by ghost** [comment]
We're reorienting the program to be more developer-focused. We appreciated all the articles, and hopefully some of them contributed to the long-term health of the community, but no, we will not be distributing any more content bounties.
