### ISSUE TITLE
Hydrogen - Educational Content 

### ISSUE THREAD

**Issue by donlast** [HydroBlockchain/hcdp#113]
https://medium.com/@donsheriff8/hydrogen-the-public-ledger-for-financial-services-f2ddd3f9e71

0x2C063454A8D52D2ad71c801430ed7107F236938E

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
