### ISSUE TITLE
Educational Content Hydrogen — Building the Financial Web 3.0

### ISSUE THREAD

**Issue by yakupaydin** [HydroBlockchain/hcdp#114]
https://medium.com/@yakupaydinyakup/hydrogen-building-the-financial-web-3-0-f5dfbeac8c2c

0xd07383fb1be59b83bf8c2c6bc6de605db882735f

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
