### ISSUE TITLE
Integration of payment api into hydro community

### ISSUE THREAD

**Issue by viczeph** [HydroBlockchain/hcdp#119]
**What language is it in?**
English
**Any important links?**
https://medium.com/@viczeph/intergration-of-payment-api-into-hydro-community-b25d8362e187
**Ethereum Address**
0xCBACc685184134635bF3ed3e74E0730877fD5fbB

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
