### ISSUE TITLE
Informative content

### ISSUE THREAD

**Issue by Ofohchibuike** [HydroBlockchain/hcdp#121]
https://medium.com/@ofohchibuike?source=post_header_lockup

0xa2527c0808d47b5C2ba9Be1D0407474b14eC3F71

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
