### ISSUE TITLE
HYDRO; AN IMMUTABLE LAYER OF SECURITY ON SENSITIVE DATA WITH BLOCKCHAIN BASED AUTHENTICATION

### ISSUE THREAD

**Issue by oly4life** [HydroBlockchain/hcdp#124]
https://steemit.com/blockchain/@olyonyeka/hydro-an-immutable-layer-of-security-on-sensitive-data-with-blockchain-based-authentication

0xa12bCf1159Aa01C739269391AE2d0BE4037259f3

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
