### ISSUE TITLE
Integration of KYC api in Hydro community

### ISSUE THREAD

**Issue by viczeph** [HydroBlockchain/hcdp#129]
**What language is it in?**
C#
**Describe how to use it**
C# library
**Any important links?**
https://github.com/viczeph/prototype-c-for-hydro-KYC
**Ethereum Address**
0xCBACc685184134635bF3ed3e74E0730877fD5fbB
**Other important information**
``sorry for the way the program looks am not an expert at using Github. Thank you

**Comment by ghost** [comment]
This example is not up to any reasonable standard.
