### ISSUE TITLE
jHydro: java Wrapper for RainDrop Hydro API

### ISSUE THREAD

**Issue by jzafrap** [HydroBlockchain/hcdp#13]
**What language is it in?**
Java (Jre10 required)
**Describe how to use it**
Java developers can use this API to integrate their Apps with Hydro API. Source code included to download and simply call service methods. 
**Any important links?**
GitHub (in progress, initial work submitted): https://github.com/jzafrap/Jhydro
**Ethereum Address**
0x4Ef7f46b3aaD6DEfd77e6C2662B987f21F72D283
**Other important information**

**Comment by ghost** [comment]
Since we will be updating our API very soon, this SDK will require changes. We will ping you once these changes are live, and if you are interested in maintaining/updating your codebase then we can discuss further at that point.

**Comment by ghost** [comment]
Closed per #209
