### ISSUE TITLE
The Hydrogen project and Hydrogen Atom 

### ISSUE THREAD

**Issue by daisy28** [HydroBlockchain/hcdp#132]
https://steemit.com/daisy28/@daisy28/the-hydro-project-and-hydrogen-atom
 
0xad771B7AD5F67ACF4258dC8Fb147De715CD4D993

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
