### ISSUE TITLE
EDUCATIONAL CONTENT:HYDRO CRYPTOCURRENCY.

### ISSUE THREAD

**Issue by ifeoma419** [HydroBlockchain/hcdp#133]
https://steemit.com/hydro/@jupitar/hydro-cryptocurrency

0x955A233f99340215Fb70Af8Ca1882faF1F370D99

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
