### ISSUE TITLE
HYDROGEN API-SECURE YOUR DOCUMENTS, PERSONAL DATA AND EFFECTIVELY MANAGE YOUR ACCOUNT

### ISSUE THREAD

**Issue by johnomonday53** [HydroBlockchain/hcdp#136]
https://steemit.com/ico/@johnomonday/hydrogen-api-secure-your-personal-data-documents-and-effectively-manage-your-account

Ethereum address:
0x8bbFa143401ADdadd166B8Ec06989092D1733EAb

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
