### ISSUE TITLE
Educational Content 

### ISSUE THREAD

**Issue by nefscharlie** [HydroBlockchain/hcdp#137]
https://steemit.com/hydro/@nefscharles/hydro-2fa-raindrop-the-future-of-2fa-123c054ff02de

0x5FEcAa3e1771eBA4B418B32b5Bc2F6E645Abe60f

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
