### ISSUE TITLE
Education content

### ISSUE THREAD

**Issue by DanEbri** [HydroBlockchain/hcdp#138]
*Hydro,   the next generation  2FA 

On the blockchain Ethereum, exist hydro. 
"Hydrogen aims to revolutionize the financial system by leveraging the power of Blockchain. Hydro enables new and existing private systems to seamlessly integrate and leverage the immutable & transparent dynamics of a public blockchain to enhance application and document security, identity management, transactions, and artificial intelligence. Hydrogen is the building block for financial life. Hydrogen can be seen as securing your financial assets"

To guide against hacks, protect our data, Information etc. Since either you or someone you know have lost a valuable asset online due to one form of inadequate security or another. 

Our data on the internet has to be well protected and this gave rise to Google's Two Factor Authentication popularly known as 2FA.

Two Factor Authentication is a “multi factor authentication” that requires not only a password and username but also something that the user should know or have immediately to hand like a physical token.

There are currently two 2FA products on the market presently, which are: Google Authenticator and Authy. Most people when they hear about 2FA Apps, they typically first come across Google Authenticator for protection, because Google permeates so much of the internet, anyway. In terms of security they both provide a service for extra security, although they both have disadvantages like the lack of multi-device support. If you are using Google 2FA, then you’ll tied to a single device, so if you want to register a new phone or tablet, Google Authenticator automatically unregisters your current device.

Google Authenticator is not on the blockchain network which makes it centralized. This means that once the 2FA app server is down, your Authenticator will be down as well. depending on your phone number as part of your identity. That means, if there is a system breach on your mobile number’s service provider, your security will be a risk and your 2FA App will no longer protect your data. 

HYDROGEN 2FA — Raindrop (first product) 

Hydro is a platform which makes it possible for new and existing organizations to utilize the features of blockchain technology in order to ensure the security of information, transactions, sensitive documents etc.

Hydro first product release is called “Raindrop” — a transaction performed through a smart contract that validates and authenticate private system access publicly. The technology is intended to provide additional security layer for sensitive financial data that is increasingly at risk from hacking and breaches.

"Hydro Raindrop involve whitelisting of each user you desire to authenticate with the Hydro API. Requesting a challenge string from the Hydro API. Perform the raindrop, which happens outside of the Hydro API, on the Hydro Smart Contract. Authenticate on the Hydro API. Once the raindrop has been completed and confirmed in the blockchain final authentication can be performed. Raindrop has been a huge success. It allows anyone running a private API to secure access using a public blockchain"

Erc20 
0xd876668cDd4C8B6f54E8F0A8DAdC71dC059BdeFa

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
