### ISSUE TITLE
 Educational Content

### ISSUE THREAD

**Issue by chaturangasri** [HydroBlockchain/hcdp#139]
**Link to the posted content**
https://medium.com/@nipunsri/new-era-of-blockchain-technology-hydro-tokens-9c8c47cb4d8a
**Ethereum Address**
0x07A111a4A1786CDbf97e7d1CAa8713409Ee31aDe

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
