### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by nguyenduyanh01** [HydroBlockchain/hcdp#140]
**Link to the posted content**
https://youtu.be/ciEUGEExqPk
**Ethereum Address**
0xD2eF313B34Ba09e2500d3640066Ea0d5C59e14D0

**Comment by nguyenduyanh01** [comment]
I am very impressed with this project, I made this overview video to introduce to my friends. They will be introduced to the HYDROGEN project, helping them to understand the project information and to develop a sound investment policy into this project.

**Comment by ghost** [comment]
No content that speculates on token price, trading, or attempts at market manipulation will be considered.
