### ISSUE TITLE
Educational

### ISSUE THREAD

**Issue by thodorisanta** [HydroBlockchain/hcdp#142]
**Link to the posted content** https://medium.com/@oshikurou/what-makes-hydrogen-hydro-special-245cfa4da016

**Ethereum Address** 0x3a26d11a8883df7518a968ee20a27f9e2bb48784

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
