### ISSUE TITLE
Security, User Interface, Data, SalesForce Integrations

### ISSUE THREAD

**Issue by cyphercodes96** [HydroBlockchain/hcdp#143]
**What language is it in?**

Java / JavaScript / Python
AngularJS / Angular 6 / Node / Django / Flask

**Ethereum Address**

0x3C567A3C5EB0Dc5aBac02FDF5e0B31e84dC52c8f

**Other important information**

I'm an experienced Software Engineer, Looking forward to contributing with your projects

**Comment by ghost** [comment]
Hi @cyphercodes96, we've changed the structure of the HCDP a bit. It will now be centered around specific projects with clearly defined deliverables, timelines, etc. I'm closing this particular issue out, but feel free to continue monitoring open issues for ongoing development tasks!
