### ISSUE TITLE
HYDRO - A Systematic approach to enhance a scalable financial decentralized solution

### ISSUE THREAD

**Issue by segunjosh** [HydroBlockchain/hcdp#144]
**Link to the posted content**
https://steemit.com/ico/@brindocorp/hydro-a-systematic-approcah-to-enhance-a-scalable-financial-decentralized-solution

https://medium.com/@segunjoshua/hydro-a-systematic-approach-to-enhance-a-scalable-financial-decentralized-solution-530557d25f0e

**Ethereum Address**
0x16C4184177e18E440a691Bd7A0178d8065B0Efb4

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
