### ISSUE TITLE
Pyhton Whitelist Integration

### ISSUE THREAD

**Issue by yakupaydin** [HydroBlockchain/hcdp#145]
https://medium.com/@yakupaydinyakup/hydro-pyhton-whitelist-integration-893d3a448b48

0xd07383fb1be59b83bf8c2c6bc6de605db882735f

**Comment by ghost** [comment]
We've already developed a Python API for Raindrop.

**Comment by yakupaydin** [comment]
İt just educational content to tell people how it easy to use whitelist api.
