### ISSUE TITLE
integrations and expansions

### ISSUE THREAD

**Issue by murphy2mm** [HydroBlockchain/hcdp#148]
i am a medical doctor who's in a private practice setting in Nigeria,Africa.
my hospital is progressively working and have developed some apps for authentication as regards our financial accountability but i have been unable to link with google authentication and want to use your hydrogen platform since it promises to be simpler and cost effective.i gladly wish to participate in using the hydrogen coin for authentication. 0x7470fbC1ae8d09E1AB30C61F4A6c485C92b99D84
below is attached my medical certificate of qualification
[mdcn full registration.pdf](https://github.com/hydrogen-dev/hcdp/files/2027378/mdcn.full.registration.pdf)
[mdcn 2018 licence.pdf](https://github.com/hydrogen-dev/hcdp/files/2027380/mdcn.2018.licence.pdf)

**Comment by ghost** [comment]
Please contact our sales team if you're interested in integrating Hydrogen products: https://www.hydrogenplatform.com/contact
