### ISSUE TITLE
Hydrogen Infographic

### ISSUE THREAD

**Issue by Horhe24** [HydroBlockchain/hcdp#149]
Imgur Link: http://imgur.com/FAlnrAC
Twitter Link:
https://twitter.com/HepHepHorhe/status/999083912654610432?s=19

Ethereum Address:
0x615cB3Ded6DEACE101EA22746F181E5e30DC5968
Email address: george_024@ymail.com

**Comment by ghost** [comment]
We are no longer accepting content as part of the HCDP. Thank you for your submission.
