### ISSUE TITLE
Hydrogen Raindrop Introduction

### ISSUE THREAD

**Issue by novocaine1926** [HydroBlockchain/hcdp#15]
**https://steemit.com/hydro/@pahrtenope/hydrogen-raindrop-security-blockchain-introduction**

**0xA7660B832Ee1f3E2224683fc0cfdee9ffc02b366**

**Comment by ghost** [comment]
Thanks for the article @novocaine1926! An interesting read, but unfortunately it doesn't quite meet HCDP standards. We appreciate the effort, thanks for being part of the Hydro ecosystem.
