### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by spywebra** [HydroBlockchain/hcdp#150]
Content submission
http://www.atgnews.com/2018/05/hydrogen-platform-hydrogen-platform.html
Wallet:- 
0x51A3f1c39742B9fE1fD6bb8BbF795dECb6229D1e

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.

**Comment by spywebra** [comment]
It's all right no problem
