### ISSUE TITLE
educational content

### ISSUE THREAD

**Issue by pushpatai** [HydroBlockchain/hcdp#151]
https://steemit.com/ico/@managavep/hydrogen-raindrop-platform-information

0x35d0db137Dc5E8178Ffc53Ae3a6658493fFB4bcA

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
