### ISSUE TITLE
SDKs & Libraries

### ISSUE THREAD

**Issue by lizzyGLO** [HydroBlockchain/hcdp#152]
What language is it in? C# and .Net

Describe how to use it
A class library defines types and methods that are called by an application. A class library that targets the .NET Standard 2.0 allows your library to be called by any .NET implementation that supports that version of the .NET Standard. When you finish your class library, you can decide whether you want to distribute it as a third-party component or whether you want to include it as a bundled component with one or more applications.

Any important links?
https://github.com/lizzyGLO/hydrodatabase/blob/master/README.md

Ethereum Address
0xb98925ee569A1BDbF7EF74C972a7148642a82118

Other important information
the .NET Framework is the underlying library for all .NET languages. This is a huge library of functions that is programming language-independent, meaning that any programming language targeted at the .NET platform can make use of this functionality.

The importance of this underlying set of types and members cannot be overstated; developers in any language will have access to the same types, and they will behave exactly the same way in any .NET language. If you need to create a multithreaded application, for example, you use the threading classes present in the .NET Framework, instead of having to rely on your language of choice having built-in support for multithreading. While the actual syntax to call the objects varies from language to language, the object is the same across all languages, because they are created from the .NET Framework base class.

**Comment by ghost** [comment]
Since we will be updating our API very soon, this SDK will require changes. We will ping you once these changes are live, and if you are interested in maintaining/updating your codebase then we can discuss further at that point.

**Comment by lizzyGLO** [comment]
I'm interested in maintaining/updating my codebase. And also wanna to introduce: HIBERNATE it's also an advance Java programming language for mapping databases. Thanks.

**Comment by ghost** [comment]
On further review, this submission is not up to reasonable standard.

**Comment by lizzyGLO** [comment]
I can try out some standard codes build on c#. Can re submit another issue?

**Comment by lizzyGLO** [comment]
I can try out some standard codes build on c#. Can re submit another issue?

**Comment by ghost** [comment]
Yes.
