### ISSUE TITLE
HDRO - BUILDING A MORE SECURE PRIVATE SYSTEM

### ISSUE THREAD

**Issue by Elmichaels** [HydroBlockchain/hcdp#153]
**Link to the posted content**
https://steemit.com/blockchain/@elmichaels/hdro-building-a-more-secure-private-system
**Ethereum Address**
0xA9334e54F7627332bC581d6dd6fD94aB79b39E55

**Comment by AnuragHydro** [comment]
Hi, thanks for your submission! We are not currently accepting content that summarizes or rephrases existing, widely available content.
