### ISSUE TITLE
Integrations and expansions

### ISSUE THREAD

**Issue by templar97** [HydroBlockchain/hcdp#155]
**What language is it in?**
visual basic
**Describe how to use it**
visual basic developers can simply use this to interact with the hydro api, view the readme for more information.
**Any important links?**
https://github.com/templar97/Hydro-project
**Ethereum Address**
0x7FA9b0A44613c4c35183B534FbF389e142662aa9
**Other important information**

**Comment by ghost** [comment]
Since we will be updating our API very soon, this SDK will require changes. We will ping you once these changes are live, and if you are interested in maintaining/updating your codebase then we can discuss further at that point.

**Comment by Solali** [comment]
Integration of Hydro into the Banking System. The software is still at early stage of development but it is aimed at integrating the Hydro Raindrop into the current existing banking apps. It is written with VB.NET
ETH Address: 0xcdfAb7118bAE98eFCFd2cb03dcf368ebbf6E0B10

**Comment by ghost** [comment]
@Solali at this time, we don't see visual basic as a high priority for Raindrop SDKs. Thank for your submission, and please follow along as additional development bounties are posted!

**Comment by Solali** [comment]
Thanks for your reply.

Can I participate in other Hydro community development bounties still
ongoing?

**Comment by ghost** [comment]
Absolutely! We'd be more than happy to have you continue to be a part of the ecosystem, please check back periodically for development bounties as they're posted.
