### ISSUE TITLE
 JAVA Hydrogen raindrop api library

### ISSUE THREAD

**Issue by simplejay** [HydroBlockchain/hcdp#156]
**What language is it in?**

Built with Java

**Describe how to use it**
`

<h2><a id="user-content-getting-started" class="anchor" aria-hidden="true" href="#getting-started"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path></svg></a><a id="user-content-getting-started" href="#getting-started"></a>Getting Started</h2>
--
  | <pre><code> IHydroAuthenticator hydroAuthenticator = new HydroAuthenticator("API_KEY", "API_USERNAME", "USE_TESTNET true/false");
  | </code></pre>
  | <h3><a id="user-content-step-1-add-address-to-whitelist--be-careful-for-security-purposes-this-id-will-only-be-generated-one-time-" class="anchor" aria-hidden="true" href="#step-1-add-address-to-whitelist--be-careful-for-security-purposes-this-id-will-only-be-generated-one-time-"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path></svg></a><a id="user-content-step-1-add-address-to-whitelist--be-careful-for-security-purposes-this-id-will-only-be-generated-one-time-" href="#step-1-add-address-to-whitelist--be-careful-for-security-purposes-this-id-will-only-be-generated-one-time-"></a>Step 1: Add address to whitelist ( be careful, for security purposes, this id will only be generated one time. )</h3>
  | <pre><code>Whitelist whitelist = hydroAuthenticator.whitelist("Hydro/Ethereum ADDRESS 0x12312...");
  | <p>whitelist.isSuccess(); //api call is success (200)
  | whitelist.getMessage(); //error response content</p>
  | </code><p><code>whitelist.getHydroAddressId(); //get address id
  | </code></p></pre><p></p>
  | <h3><a id="user-content-step-2-get-raindrop-details" class="anchor" aria-hidden="true" href="#step-2-get-raindrop-details"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path></svg></a><a id="user-content-step-2-get-raindrop-details" href="#step-2-get-raindrop-details"></a>Step 2: Get Raindrop details</h3>
  | <pre><code>Challenge challenge = hydroAuthenticator.challenge("HYDRO_ADDRESS_ID");
  | <p>whitelist.isSuccess(); //api call is success (200)
  | whitelist.getMessage(); //error response content</p>
  | <p>// Set quantity of Hydro tokens to send to the blockchain. Since our token has 18 decimal places, the number that you will need to send may seem large, but remember that the 18 rightmost digits are actually decimals. For example, 313823208533000000 is actually .313823208533000000 Hydro.
  | challenge.getAmount();</p>
  | <p>// Randomly generated string used to confirm the validity of the transaction. Only the client requesting the challenge will know the value.
  | challenge.getChallenge();</p>
  | </code><p><code>// The ID assigned to your firm which will be the same for all authentication requests.
  | challenge.getPartnerId();<br>
  | </code></p></pre><p></p>
  | <h3><a id="user-content-step-3-check-on-exist-valid-raindrop-transaction" class="anchor" aria-hidden="true" href="#step-3-check-on-exist-valid-raindrop-transaction"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path></svg></a><a id="user-content-step-3-check-on-exist-valid-raindrop-transaction" href="#step-3-check-on-exist-valid-raindrop-transaction"></a>Step 3: Check on exist valid Raindrop transaction</h3>
  | <pre><code>Authenticate authenticate = hydroAuthenticator.authenticate("HYDRO_ADDRESS_ID");
  | </code><p><code>// check is authenticated
  | authenticate.isAuthenticated();
  | </code></p></pre><p></p>

`

**Any important links?**
https://github.com/simplejay/hydro-auth

**Ethereum Address**
0x0D3295e1eDe774f622c74E5749714Bec6793A73c

**Other important information**

Follow the below link for a more detailed code snippet https://github.com/simplejay/hydro-auth

**Comment by ghost** [comment]
Since we will be updating our API very soon, this SDK will require changes. We will ping you once these changes are live, and if you are interested in maintaining/updating your codebase then we can discuss further at that point.

**Comment by simplejay** [comment]
Hello,
Thanks for getting back to me. I will make the necessary changes once your Api is updated. However, I do like to know if I'm qualified for the HDB. If yes, when should I expect the token.

Thanks,
Awaiting your best response.

**Comment by ghost** [comment]
Closed per #209
