### ISSUE TITLE
Educational content

### ISSUE THREAD

**Issue by Spicytee16** [HydroBlockchain/hcdp#157]
**Link to the posted content** https://steemit.com/cyrptocurrency/@queentee/hydro-enables-private-financial-system-to-leverage-on-public-blockchain

**Ethereum Address** 0x9C082fddd11A252d273aEcE6dD734090f0aC84aB

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
