### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by Akuma215** [HydroBlockchain/hcdp#158]
https://medium.com/@robert.danial/feelings-introduce-hydrogenplatform-light-and-modular-apis-5a8f513b57da

0x69814FC1eC14C845ba3EAF710d0006E0C0AE8292

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
