### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by safreen18** [HydroBlockchain/hcdp#159]
https://steemit.com/blockchain/@safreen/hydrogen-worldwide-ecosystem

0x45a6aF8D5A89ba74E096AECA6A5d696E4AB06f34

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
