### ISSUE TITLE
Integrations & Expansions

### ISSUE THREAD

**Issue by Narpheey** [HydroBlockchain/hcdp#16]
**What language is it in?**
C# (ASP.NET MVC 5)

**Describe how to use it**
Using the hydrogen Snowflake-Blockchain Fingerprint to create a unique identity for farmers interested in loans from agricultural financial institutions(Micro finance banks) and keep track of loan transactions.

PROBLEM 
Farmer A walks into Bank A to request for a loan which gets approved and to be paid installmentally(6 payments) over a period of time. Farmer A pays two installments and walks away.
Farmer A goes to bank B to request for another loan. Bank B is totally unaware that Farmer A has outstanding loan in Bank A.

SOLUTION

Decentralized farmer/loan app for managing farmers, loan transactions and records.

 
**Any important links?**
Null

**Ethereum Address**
0x3A49BA7a597A1B1de934eD51B8E5a5E1D91596D2

**Other important information**

**Comment by AndyHydro** [comment]
Hey, this is a really cool idea and we would love to help you work to complete it! We are currently only accepting completed projects, but I would like to encourage you to head over to our dev discord server so we can talk more about helping you complete your project! https://discord.gg/zYZEabW
