### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by williewonker** [HydroBlockchain/hcdp#160]
https://medium.com/@f4caf8a0919/5658fed89674

0x4fCe7bE55c189C44aD00B6b5c7Aad57858c261a2

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
