### ISSUE TITLE
Educational content 

### ISSUE THREAD

**Issue by Abisola07** [HydroBlockchain/hcdp#161]
https://medium.com/@abisolaharajukubarbie/creation-of-a-new-digital-economy-7d569488d540?source=linkShare-caabef0f8ba-1527044693                           

0x99Ee0e905141C1e5335B9E5Fe5a984A6e03Ab431

**Comment by Abisola07** [comment]
Please approve me as this project means a lot to me. Thanks

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
