### ISSUE TITLE
Integrations & Expansions

### ISSUE THREAD

**Issue by IMSOFNET** [HydroBlockchain/hcdp#162]
**What language is it in?**
It is an app written in Android, Java and C++.

`//Unlock level`
`private int getToken(int num){`
`      // Code integration to connect to Hydrogen API.`
`       if(token == HYDROGEN_API.getSmartContract){`
`        return Hydrogen.getToken(num)`
`      }`
`}`

**Describe how to use it**
English Vocabulary Trainer offers an advanced, interactive program that enables students and adults to master a hand-picked list of more than 2400 English vocabulary words. It helps to build student's vocabulary and word power -- for personal, professional, career, or educational (test-prep) purposes. It also helps in mastering English vocab for TOEFL, IELTS, GRE, SAT and other exams.

The first level is designed to be free, while Hydrogen token will be required to access other levels instead of the formal 'little stars' used. The Hydrogen API and the smart contract will be integrated as In App Purchasing and this will make the overall result a tangible sense of progress that makes vocabulary learning a pleasure instead of a chore.

![image](https://user-images.githubusercontent.com/30845597/40403838-5ff24722-5e4c-11e8-911d-5d8eadfcb234.png)

**Any important links?**
It is already published on the Google Play Store without the integration. The integration will follow the updates. 
[https://play.google.com/store/apps/details?id=com.imsofnet.apps.englishvocabularydeveloper](url)
**Ethereum Address**
0x7be9eBFd4E441450cC6c5deDFCD370ECaBC36cB8

**Other important information**
English Vocabulary Trainer app provides a highly focused, interactive learning environment that allows everyone to improve their English language skills rapidly. Practicing the words learnt is an excellent way to master the new vocabulary. They can then commit this knowledge to long-term memory by testing their self in a variety of ways. Words and phrases are carefully selected with reference to previous input, encouraging them to concentrate on those they find difficult. Feedback is immediate and informative, without any distracting special effects. Hydrogen API will be integrated in the next update as In App Purchasing.

**Comment by ghost** [comment]
Per our wiki: "Please only submit projects that you've completed or are actively developing. This is not a space for feedback or proposals."
