### ISSUE TITLE
Document Translation

### ISSUE THREAD

**Issue by kelechiforex** [HydroBlockchain/hcdp#169]
Translation in Sudanese language 
0x0c0350be5151f3AF07CdECfC09AD2200eCa8f0b6
[Hydro_Raindrop_White_Paper_Sudanese.pdf](https://github.com/hydrogen-dev/hcdp/files/2030605/Hydro_Raindrop_White_Paper_Sudanese.pdf)

**Comment by kelechiforex** [comment]
A great project that will definitely change the evolution of cryptocurrency

**Comment by ghost** [comment]
We are not accepting whitepaper translations at this time.
