### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by Romanbank** [HydroBlockchain/hcdp#170]
https://steemit.com/steemitcrypto/@romanbank/hydro-raindrop-the-blockchain-authentification

0x343A5C0d966E3F8EA004Efb8939c7D71A60ae795

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
