### ISSUE TITLE
Raindrop: THE ADDITIONAL LAYER OF SECURITY

### ISSUE THREAD

**Issue by PhilMovs** [HydroBlockchain/hcdp#171]
https://steemit.com/hydro/@philmovs/raindrop-the-additional-layer-of-security

0xC23A42cB86E3a260b7bf119fAF914730beDaCBAf

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
