### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by ebykamsi** [HydroBlockchain/hcdp#172]
https://steemit.com/blockchain/@ebykamsiokoro/the-hydro-raindrop-security-revolution

0x8Acd65aFAcd8F326F65479515F7e015dFa04d904

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
