### ISSUE TITLE
Educational Content in Bangali What is Hydrogen Platform

### ISSUE THREAD

**Issue by zahid01753** [HydroBlockchain/hcdp#178]
Language: Bangali

**Ethereum Address**   0xbb34CAdaeb62520483c7f4d2986429bd0d9d5794

[Educational Content in Bangali What is Hydrogen Platform.docx](https://github.com/hydrogen-dev/hcdp/files/2036193/Educational.Content.in.Bangali.What.is.Hydrogen.Platform.docx)

https://www.reddit.com/r/ProjectHydro/comments/8ltnar/educational_content_in_bangali_what_is_hydrogen/

Email: shunnolove@gmail.com

**Comment by zh0076463** [comment]
thanks sir

**Comment by timingtrader** [comment]
(Language: English)

Hi,

I must suggest to invest in **HYDRO**, it's a project with a scary
potential growth!

Here, some explanations:

http://www.crypto-valute.it/post-cryptovalute/428-hydrogen-platform-security-hydro-crypto-a-must-invest-altcoin.html

**Ethereum Address**: 0x72F92aD7faF1073481Aa395EB165903fB9843977

**Comment by zahid01753** [comment]
thanks you sir

**Comment by ghost** [comment]
We are no longer accepting content submissions as part of the HCDP. Thank you for your submission.
