### ISSUE TITLE
FINANCIAL TECHNOLOGY- THE HYDRO ADVANTAGE

### ISSUE THREAD

**Issue by amosudokaogu** [HydroBlockchain/hcdp#181]
Content link: https://www.linkedin.com/pulse/financial-technology-hydro-advantage-amos-udokaogu/?published=t

Eth address: 0xB2462Cb4187255e1B2c56C8711De6252aB60E916

**# FINANCIAL TECHNOLOGY – THE HYDRO ADVANTAGE**

Cryptocurrencies came into the scene as a game changer and they have, for a good course, revolutionized the idea of monetary exchange as an intangible asset. With a big break into the fintech space, they are improving the ecosystem with layers of security. Significant among the remarkable features is the total elimination of the middleman.  
Cryptocurrency, from a simplistic point of view is digital money that is designed to be a means of exchange in a virtual community.
Bitcoin being the first to blaze the trail in the crypto world has done well for itself as a leader in this space.  Bitcoin has its own technology which makes it unique and revolutionary. It uses its own blockchain technology to perform its transactions in a decentralized manner. Eventually, Ethereum technology emerged with its own unique features too. Ethereum operates its own platform that allows developers and other cryptocurrencies to use Ether blockchain infrastructure. One of Ether’s unique technology is the smart contract.
However, I am here to make a case for Hydro Technology. The newest innovation in the fintech space which proves to have a system that is built to help circumvent hacking and security breaches. How does Hydro work? Hydro creates a private system called the Hydro APIs to use its own hydro public blockchain to tighten security checks through public verification.
Hydro has three technological projects to execute which are geared towards data/information protection in the fintech world. These projects are:
Hydro APIs – It is hydro’s private system. It is basically about validating transactions through smart contracts to be accessed on a public blockchain.
Hydro Blockchain – This is a distributed public ledger that processes hydro transactions and contains hydro smart contracts.
Raindrop – This is a technology that is intended to provide additional security for sensitive financial data which is a major growing concern because of hacking and security breaches.
I will be dwelling more on the Raindrop technology and how it works on hydro system.
While other financial services platforms commonly use micro deposit verification to confirm clients’ accounts by making small deposits of random amounts in a user’s claimed bank account to prove the ownership of the said account, Hydro raindrop contains condensed functionalities that vary in velocity, shape and are unpredictable. 
Hydro’s authentication of transaction is unique and practically impossible to happen by chance. Hydro raindrop’s verification is manually performed. This means that before a transaction is defined, the user must access it from a known wallet. Also, raindrop features an immutable public ledger and authorization attempts are monitored by the system and accessor.
Meanwhile, for a hydro authentication process to occur, there are four entity level interactions which must happen:
•	Accessor – the party issuing the command – Financial institution or the platform using the Hydro APIs.
•	System – The gateway where command is being performed – Hydro API itself.
•	Hydro – The module that is utilized by the system to interface with the blockchain.
•	Blockchain – The distributed public ledger through which information/transaction can be performed on.
The Raindrop technology has five transactional parameters. They are:
•	Sender – The address that must initiate the transaction.
•	Receiver – The transaction destination.
•	ID – An identifier that is associated with the system.
•	Quantity – A precise number of Hydro to send.
•	Challenge – A randomly generated alphanumeric string.
Raindrop is built to solve the problem of rising vulnerability in the fintech space through its offering of a distinct, immutable, globally viewable layer of security that verifies that an access request is coming from an authorized source.
Financial platforms are usually the gateways for massive private and sensitive data such as ID number, and account credentials. Thus, there have been cases where these information and data were largely compromised because of hacking and security breaches.
Sighting the study by Javelin strategy & research (2017 Identity Fraud Study), $16 billion was stolen from 15.4 million people in the U.S. This is probably a fraction of the global amount of money lost to hackers and cyber theft.
Hydro as an emergent technology will improve the fintech security space and practically make security breaches a near impossibility due to the second layer level of authentication employed by the technology.  Playing the devils advocate here, a breach can only occur if the attacker has access to the Accessor’s private wallet key and of course the system credential. How is this possible? I am waiting to be proven wrong.
Hydro technology is the solution to fintech security breaches and the earlier this is adopted globally, the less the financial loss to attackers and hackers.
The future is bright for the fintech world and the permanent solution to cyber theft has come finally.

**Comment by ghost** [comment]
We are no longer accepting content submissions as part of the HCDP. Thank you for your submission.
