### ISSUE TITLE
HYDROGEN PLATFORM - Understanding the Hydrogen Project

### ISSUE THREAD

**Issue by beebeehem** [HydroBlockchain/hcdp#183]
https://medium.com/@beebeehem/hydrogen-platform-understanding-the-hydrogen-project-812bc335d29d
Ahmed Rasheed
0x005B2d2cFa129c7d9aC311F6098d879Cf6804E7D

**Comment by ghost** [comment]
We are no longer accepting content submissions as part of the HCDP. Thank you for your submission.
