### ISSUE TITLE
Hydro Raindrop for Securing FinTech.

### ISSUE THREAD

**Issue by kingsamosy** [HydroBlockchain/hcdp#184]
https://steemit.com/crypto/@kingsely/hydro-raindrop-for-securing-fintech

0xBBfD2dC6763F1Eb169Aa2D648Cee309159775B6E

The finance world is now redefined by advanced technology. The 21st century now includes technology and innovation that aims to compete with traditional financial methods in the delivery of financial services. Fintech (financial technology) as it now called is made so with the use of smartphones for mobile banking, investing services, and cryptocurrency to make services more accessible to the public.
To ease usage and fast track this integration, various APIs (applications) have been developed.
As it is, financial platforms are gateways to large quantities of private and sensitive data such as government ID numbers, account credentials, and transaction histories.
Unfortunately however, the existing financial system does not have a fool-proof system when it comes to preventing, diagnosing, and communicating data breaches with its stakeholders.
The rise of the data age has brought with it a rise in vulnerability, and this is particularly important for financial services. As a result of the sensitive nature of financial data, unwarranted access is typically met with catastrophic results.
Without doubt, the major challenge faced by Fintech organisations is data security. The protection of sensitive consumer and corporate financial data is important.
This is why Blockchains are now being introduced into private systems, such as APIs, especially fintech apps in investing, savings, or insurance.
Hydrogen Technology Corporation, has as a result of this, utilised blockchain technology in advancing protection of data and preventing breach. This is done by empowering developers of APIs to integrate what it calls the “Hydro Raindrop” in their existing applications without the need to create expensive infrastructure.
Any platform - be it an API, application, enterprise software, gaming platform, etc. – can leverage Hydro for authentication purposes.
What is Hydro Raindrop?
The integrity of financial data gateways can be improved with an additional layer of security via Hydro.
This technology, already implemented on the Ethereum cryptocurrency network, ensures transactional validity because participants collectively process transactions that are properly signed.
This reality leads to decentralization and immutability, but, more importantly, it provides a vector for mitigating unauthorized access to a gateway that handles sensitive data.
With Hydro, authentication can be predicated upon transactional operations on the blockchain. An API, for example, can choose to validate developers and applications by requiring them to initiate particular transactions, with particular data payloads, between particular addresses on the blockchain, as a precondition that kickstarts a standard authentication protocol.
There are dozens of ways the Raindrop release can be used by private organizations. Although private APIs, databases, and networks have created elaborate systems of tokens, keys, apps, and protocols over the last decade, in an attempt to secure sensitive data. There is little to no reason to compete with or replace these existing protocols.
How Hydro Raindrop works to reinforce security.
Here is a brief overview of how Hydrogen implements Hydro authentication as a security layer in its overall API security framework:
• Hydrogen API partners must first have the IP addresses of their various environments whitelisted.
• Partners must request to whitelist a public Hydro address.
• All calls to the Hydrogen APIs and transfers of data are encrypted and transmitted through the HTTPS protocol.
• Partners must complete a valid Hydro raindrop transaction from the registered Hydro address.
• Partners must use OAuth 2.0 validation. OAuth (Open Authorization) is an open standard for token-based authentication and authorization. Hydrogen supports the “Resource Owner Password Credentials” and “Client Credentials” grant types, and each API user must provide credentials for an authentication request.
• If none of the five elements above are violated, the Hydrogen partner is granted a unique token, to be checked and verified with each API call.
• The token is valid for 24 hours, after which the partner must validate themselves again.

Thus, if any of these steps is violated, the user is immediately locked from API access. A hacker cannot bypass these security factors by guessing randomly, because there are trillions of unique combinations.
API hackers can now be thwarted with more immediacy because of the ability to detect unexpected authorization attempts in real-time, from anywhere in the world.

**Comment by ghost** [comment]
We are no longer accepting content submissions as part of the HCDP. Thank you for your submission.
