### ISSUE TITLE
Securing Fintech with Hydro Raindrop

### ISSUE THREAD

**Issue by monycinta** [HydroBlockchain/hcdp#186]
https://www.linkedin.com/pulse/securing-fintech-hydro-raindrop-chukwunonso-amos

0x184923a184108680EFE7Ef3cF3a9b4892F141E18

The perception of money has already changed with the emergence of blockchain technology and the birth of cryptocurrencies.

The world of cryptocurrency now allows for digital assets as a means of exchange. Digital assets are now used peer-to-peer to interact directly without the need for an intermediary.

The problem early attempts at digital currency faced is how to ensure the same currency is not used for multiple times. It also faced the issue of eradicating the need of a trusted or central authority that may make transactions more costly and cumbersome.

All these prime problems were what was eliminated with the emergence of Bitcoin, Ethereum, and the other popular cryptocurrencies.

This innovation was made possible with the introduction of Blockchains – which has now become the world’s most popular digital wallet. Blockchains are essentially public digital ledgers used to record transactions across many computers so that the record cannot be altered retroactively. Thus, all transactions are linked and secured using cryptography.

Blockchain, because of the hi-tech security it offers, is now been used to record events, medical records, and other activities like identity management, transaction processing, and even voting.

Currently, millions of users and hundreds of thousands of merchants now make use of these digital assets.

Security is however still of great concern. This is understandable because of the nature of the internet and the exposure of sensitive data to a breach.

While the blockchain seeks to ensure strict non-duplication or reuse of coins, Hydrogen Technology Corporation has introduced an innovation called Hydro Raindrop as additional security.

What Hydro Raindrop does is to enable new and existing private systems to seamlessly integrate and leverage the immutable & transparent dynamics of a public blockchain.

It is a technology that enhances application and document security, identity management, transactions, and artificial intelligence.

The Hydro Raindrop is a transaction performed through a smart contract that validates private system access publicly, and can complement existing private authentication methods.

The technology is intended to provide additional security for sensitive financial data that is increasingly at risk from hacking and breaches.

This offers a distinct, immutable, globally viewable layer of security that verifies an access request is coming from an authorized source.

Though private authentication protocols such as OAuth 2.0 already offer varying levels of their own security, Hydro facilitates a way to enhance them by incorporating blockchain mechanics as a component of an authentication procedure. This can add a useful layer of security to help thwart system breaches and data compromises.

For instance, when an Attacker steals the private key(s) to the Accessor's wallet, the accessor’s base system credential with Hydro Riandrop (which is an advanced security protocol) will stand in the way and stop the attacker from using the account to make a valid blockchain transaction.

Notably, the Hydro is already successfully implemented on the Ethereum network and is currently made available to the world developer community as open source software, to allow developers to integrate the Hydro Raindrop.

Just as Hydrogen will integrate it as a precondition for access to its API ecosystem, so too can any system add it to existing procedures and protocols.

**Comment by ghost** [comment]
We are no longer accepting content submissions as part of the HCDP. Thank you for your submission.
