### ISSUE TITLE
Education Content 

### ISSUE THREAD

**Issue by Christian764** [HydroBlockchain/hcdp#188]
https://steemit.com/blockchain/@christian764/hydrogen-public-blockchain-leveraging-hydrogen-blockchain-for-a-more-efficient-and-secured-system
ENGLISH 
ETH ADDRESS: 0xA58b3210B6F9626DFEDB9eA232E8EFc965873559

**Comment by ghost** [comment]
We are no longer accepting content submissions as part of the HCDP. Thank you for your submission.
