### ISSUE TITLE
Hydro, a good choice for peaceful investments - Top Projects' 2018 

### ISSUE THREAD

**Issue by timingtrader** [HydroBlockchain/hcdp#190]
(Language: English)

Hi,

I must suggest to invest in **HYDRO**, it's a project with a scary potential growth!

Here, some explanations:

http://www.crypto-valute.it/post-cryptovalute/428-hydrogen-platform-security-hydro-crypto-a-must-invest-altcoin.html

**Ethereum Address**: 0x72F92aD7faF1073481Aa395EB165903fB9843977

Blog Article edited for more views ;)

**Comment by ghost** [comment]
We are no longer accepting content submissions as part of the HCDP. Thank you for your submission.
