### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by ViktorSpyrantis** [HydroBlockchain/hcdp#192]
https://medium.com/crypto-centric/why-you-should-consider-using-hydrogen-encryption-9fd6c452dba6

0xF9faAF5dBF384f36Cc66e11FF045ab432c9913fb

**Comment by ViktorSpyrantis** [comment]
Just an aricle I wrote.

**Comment by ghost** [comment]
We are no longer accepting content submissions as part of the HCDP. Thank you for your submission.
