### ISSUE TITLE
SDKs & Libraries (PHP)

### ISSUE THREAD

**Issue by adrenth** [HydroBlockchain/hcdp#193]
**What language is it in?**

PHP

**Describe how to use it**

Enables easy integration to any PHP project using `composer`. Along with this package there will be packages developed for integration in popular frameworks such as Laravel and Symfony.

```composer require adrenth/raindrop-sdk```

**Any important links?**

Will be available at:
https://packagist.org

GIT Repository:
https://github.com/adrenth/raindrop-sdk

Developer information:
https://www.linkedin.com/in/alwindrenth/

**Ethereum Address**
0x094E8D8cdA1B1aD799a56358AcF3B4eaa4c35CCA

**Other important information**

Support for the latest PHP versions.

**Comment by ghost** [comment]
Pinging @adrenth, you may be interested in claiming this Wordpress bounty we just posted! https://github.com/hydrogen-dev/hcdp/issues/202

**Comment by adrenth** [comment]
Hi @NoahHydro,

There has been some progress on the PHP SDK. A first release will be out soon.
Love to hear what you think of it.

**Comment by ghost** [comment]
@adrenth it looks great so far! We'll probably formally evaluate this at the same time as the Wordpress plugin, but it seems like you're making excellent progress. Excited to see the final result!

I'll consult with the rest of team tomorrow re. an appropriate bounty amount for the PHP SDK. I know this issue stems from the old version of the HCDP, but we won't let it slip through the cracks :)

**Comment by ghost** [comment]
Closed per #208
