### ISSUE TITLE
A blog post about hydro on a paid blog site

### ISSUE THREAD

**Issue by delilonia** [HydroBlockchain/hcdp#197]
Hello, I wrote this blog post on one of the biggest paid crypto blog sites some few days ago. I was awaiting this issue to be opened not knowing it was opened and closed some hours ago. Kindly check it out and see to my efforts.

Link: https://cryptoplanet.club/hydro-project/

**Comment by ghost** [comment]
We are no longer accepting content submissions as part of the HCDP.
