### ISSUE TITLE
Request: 5000 Hydro per translation, short document translation

### ISSUE THREAD

**Issue by AnuragHydro** [HydroBlockchain/hcdp#198]
***Languages must be translated by hand by native or fluent speakers. No Google translated documents or programmatically translated documents will be accepted***

**What language do you want translated?**
German, Spanish, French, Italian

**What document do you want translated**
Text for Hydro Mobile App

**Timeframe?**
24 Hours

**Submission process?**
Comment on this issue to claim a language. Once I have confirmed, you may send me an email at anurag@hydrogenplatform.com, and I will send the file to be translated. *No more than one language per user*

**Comment by kmc09** [comment]
I claim Urdu.

**Comment by HectorBritoDev** [comment]
Let me know if you need Spanish.

**Comment by AnuragHydro** [comment]
Currently spanish is taken, but I’ll let you know if that changes!

**Comment by chibinh8** [comment]
@AnuragHydro I would like to translate to Vietnamese, please confirm

**Comment by Tcastolo** [comment]
i claim swahili

do we submit our translation to your email as well or here on github

**Comment by holadunni** [comment]
I claim Filipino

**Comment by holadunni** [comment]
I claim filipino

**Comment by Estelle002** [comment]
I claim Russian

**Comment by draco189** [comment]
I claim vietnamese

**Comment by t2ndey** [comment]
I claim Thai

**Comment by topsin4luv2000** [comment]
I claim Arabic

**Comment by AnuragHydro** [comment]
@chibinh8 - confirmed for Vietnamese; @holadunni - confirmed for Filipino; @Estelle002 - confirmed for Russian; @t2ndey - confirmed for Thai; @topsin4luv2000 - confirmed for Arabic. Please email me at anurag@hydrogenplatform.com, and I will send further instructions.

**Comment by tanukib590** [comment]
I can translate to Chinese if its not taken already.

**Comment by Meyka1305** [comment]
I claim indonesian

**Comment by angara94** [comment]
@tanukib590 - confirmed for Chinese. Please email me at anurag@hydrogenplatform.com, and I will send further instructions.

**Comment by AnuragHydro** [comment]
@tanukib590 - confirmed for Chinese. Please email me at anurag@hydrogenplatform.com, and I will send further instructions.

**Comment by Bollexz** [comment]
I volunteered to translate to Korean if it's still open please

**Comment by AnuragHydro** [comment]
@Bollexz - confirmed for Korean; please send me an email at anurag@hydrogenplatform.com for further instructions :)

**Comment by Bollexz** [comment]
Accepted
How do I go about this?

Regards
Bolarinwa Odewande

**Comment by topsin4luv2000** [comment]
I claimed Arabic

**Comment by xiaozay1** [comment]
I would like to reserve for Vietnamese translation
Native Language: Vietnamese
Tele: @HangVi
Portfolio/Experience/previous translations links:  https://docs.google.com/spreadsheets/d/1MwdgDIv4tOh10qPW5Zq432cOweSWSIIkvNNvL8voHdY/edit?usp=sharing


Contact: vivian.interpreter.exper@gmail.com
Thank!

**Comment by cyphercodes96** [comment]
I claim arabic

**Comment by tranquang9a1** [comment]
I would like to claim Vietnamese

**Comment by jhamiaseo28** [comment]
i would like to do Filipino translation.

**Comment by adeelio** [comment]
Is URDU still available. If yes I would like to claim it. Thank u

**Comment by mahofmahof** [comment]
i can handle turkish translation normally i dont translate but hydro is my favourite coin

**Comment by AnuragHydro** [comment]
@HectorBritoDev Our Spanish translator didn't complete the task. Feel free to email me at anurag@hydrogenplatform.com

**Comment by cryptoico123** [comment]
Any German translator needed?

**Comment by AnuragHydro** [comment]
@cryptoico123 yes - our German translator wasn't available. Could you send me an email at anurag@hydrogenplatform.com?

**Comment by phunkey** [comment]
I'll love to do Yoruba translation, if it's still available.  Thank you.

**Comment by Joekondo** [comment]
Hope this is not too late, I saw the message on Discord and sent you an email just now.

I'd like to reserve the Italian translation if still possible.

**Comment by dattu17** [comment]
hi sir, i like to translate in hindi.

**Comment by Joe2Code** [comment]
If you still need Filipino, I’m able to translate.

**Comment by philobbe** [comment]
Do you need french translation ?
