### ISSUE TITLE
CLAIMED 500,000 HYDRO to build a Wordpress plug-in

### ISSUE THREAD

**Issue by AnuragHydro** [HydroBlockchain/hcdp#202]
**What is the development you want done?**
[Client Raindrop](https://github.com/hydrogen-dev/hydro-docs/tree/master/Raindrop) is a multi-factor authentication (MFA) protocol developed by Hydrogen. As part of the protocol, the Hydro mobile app generates HydroIDs for users to connect them to the forthcoming ecosystem of Hydro smart contracts. This bounty is intended to foster broader adoption of Client Raindrop and the Hydro mobile app by offering website administrators tools to easily integrate Hydro MFA into their sites. Specifically, this task is to create a Wordpress plug-in that integrates with the Hydro API to offer a seamless implementation of the MFA workflow.

**What are the deliverables?**
A Wordpress plug-in that communicates with the Hydro API. The plug-in should enable Wordpress sites that manage user accounts to easily implement and manage a 2FA workflow through Hydro on their sites. 

Developers may complete this plug-in per their preference, but a suggested approach is to fork [this repo](https://github.com/duosecurity/duo_wordpress/blob/master/duo_web/duo_web.php) and adjust it to the Hydro workflow.

The [Hydro documentation](https://www.hydrogenplatform.com/docs/hydro/v1/) details the Hydro workflow. 

**Timeframe?**
We propose one month as the timeframe for completion of this task. 

**Submission process?**
First, comment on this issue to declare your willingness to complete the task. Next, send us an email at anurag@hydrogenplatform.com with a description of your tech background and qualifications. We will evaluate candidates factoring in these qualifications, Github activity, and the order in which they expressed interest. Once you have been selected, you will have one month to complete the task. During this time, we will be able to provide some support around questions about the workflow on [Discord](https://discordapp.com/invite/gxAUagw). If the task is not completed within the timeframe, we reserve the right to offer an extension or transfer the task to another candidate. Once the task is completed, we will test the plug-in for efficiency and whether or not it correctly incorporates the Hydro workflow. If we approve the plug-in, we will then send you 500,000 Hydro.

**Comment by saudi1402** [comment]
Interested

**Comment by adrenth** [comment]
Interested

**Comment by tolute** [comment]
Interested

**Comment by rdrenth** [comment]
Interested

**Comment by zoquen** [comment]
0x326a71A45a007950805C6EB0C6eE41D313009718

**Comment by velat3434** [comment]
Ilgilenen

**Comment by AnuragHydro** [comment]
Thank you for the detailed email, @adrenth  - we think you'd be a great fit and will send you a follow-up email with more information.

**Comment by uangteko** [comment]
nice project

**Comment by seunak** [comment]
Okay, I’m interested!!!
Let’s do this!

**Comment by dhopak99** [comment]
good

**Comment by zoquen** [comment]
Okay, I’m interested!!!

**Comment by avillaos** [comment]
interested

**Comment by EM8A** [comment]
Interested

**Comment by addlover** [comment]
I am interested

**Comment by Rajmahmad** [comment]
Interested

**Comment by houlaz** [comment]
i'm  interested but this 500.000 hydro for one persone or what !!?

**Comment by kemijibola** [comment]
Interested

**Comment by ecamli** [comment]
Interested

**Comment by vijay1968** [comment]
What value 500 hydro I no interested

**Comment by bestfriend1991** [comment]
I’m interested!

**Comment by cyphercodes96** [comment]
Highly interested, software engineer @ here

**Comment by colmandante** [comment]
Ok I'm interested!Let's do this!

**Comment by taunghiqua** [comment]
interested but how claim?

**Comment by burhank6161** [comment]
Interested

**Comment by pindiboy** [comment]
interested as except all projects I only like this project Hydro one of the best project

**Comment by ghost** [comment]
Hi all, per the title this project is currently claimed by @adrenth. Feel free to subscribe to the thread for updates, however, and stay tuned for more HCDP bounties in the weeks to come.

**Comment by kalempol1** [comment]
Interested

**Comment by vijay1968** [comment]
I join hydro Feb 18 after I am try to again project hydro I intersted for project hydro Ple.  Ask me prossicer what can I do for it

**Comment by ruelnueva** [comment]
Nice project Im interested

**Comment by kaysunnex** [comment]
Wish @adrenth all the best

**Comment by chiay888** [comment]
Interested. 
brdzo888@gmail.com

**Comment by HarshRajat** [comment]
Interested... Also wish @adrenth all the best

**Comment by anklunk** [comment]
Yes i'm interested & good projeck

**Comment by CryptopeX** [comment]
Yes highly interested 😍

**Comment by zoquen** [comment]
Great

Le 4 août 2018 07:43, "CryptopeX" <notifications@github.com> a écrit :

Yes highly interested 😍

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/hydrogen-dev/hcdp/issues/202#issuecomment-410428420>,
or mute the thread

**Comment by velat3434** [comment]
yes :)

**Comment by avillaos** [comment]
interested

**Comment by ghost** [comment]
huge shout-out to @adrenth and @rdrenth for successfully publishing the plugin today! It's [available on the Wordpress store](https://wordpress.org/plugins/wp-hydro-raindrop/). We've sent their [bounty reward](https://etherscan.io/tx/0x642f95b71390eec2d78770efebd93f7b7bbfd3e13e5fd0ae233fb9e70f1633f8).
