### ISSUE TITLE
Hydro OAuth2 Java Library

### ISSUE THREAD

**Issue by serkanalgl** [HydroBlockchain/hcdp#205]
Hi,

As you know that there are many hydrogen apis. This java library helps people to authorize on Hydrogen APIs. Raindrop, Snowflake etc..

For more details under:
https://github.com/serkanalgl/hydro-oauth2-java

Best regards,
Serkan Algül

**Comment by 322444** [comment]
Nice work

**Comment by vijay1968** [comment]
Great..........

**Comment by ghost** [comment]
Closed per #209
