### ISSUE TITLE
Raindrop Java Library

### ISSUE THREAD

**Issue by serkanalgl** [HydroBlockchain/hcdp#206]
Hi,

I had reported java library via google form but it's moved here. After changes on raindrop api, I made changes on my java library. Current version is supporting client and server side raindrop. 

For more details under:
https://github.com/serkanalgl/hydro-raindrop-java   (README.md is available)

Best regards,
Serkan Algül

**Comment by 322444** [comment]
Nice work

**Comment by aovacikliibc** [comment]
I have a restful api which is developed with spring boot. I want to integrate raindrop server. I found this library. It will be very helpful for my project. thank you.

**Comment by feux07** [comment]
A very useful library. We will save time on Raindrop implementations.

**Comment by ghost** [comment]
Closed per #209
