### ISSUE TITLE
Integrations and expansions (ColdFusion)

### ISSUE THREAD

**Issue by brett91ag** [HydroBlockchain/hcdp#207]
I have created a wrapper written in ColdFusion for the server-side Raindrop.  A Readme with code examples is included.  This uses the latest API with Oath.
https://github.com/brett91ag/coldfusion-hydro-raindrop

**Comment by ghost** [comment]
@brett91ag thanks for your submission! At this time, there is no active or planned HCDP bounty for a ColdFusion Raindrop SDK. This doesn't necessarily rule it out, but our impression is that ColdFusion is not particularly widely used. Is there a compelling reason that we should be aware of for sponsoring this bounty?

**Comment by brett91ag** [comment]
It would be difficult to make a compelling case for ColdFusion since its usage is on the slow decline.  There are not a whole lot of new projects using it without a doubt. But there are a large number of legacy systems using it, especially in the federal space.  ColdFusion should be around for quite a bit longer, with a 2020 release planned and support into at least 2025 from Adobe.   Even if this isn't accepted, I hope to make use of it with one of our legacy systems down the road.

**Comment by brett91ag** [comment]
perhaps consider small bounties for less popular languages like this and bigger bounties for the more mainstream languages?

**Comment by ghost** [comment]
Closed per #212
