### ISSUE TITLE
CLAIMED 200,000 HYDRO to build a Raindrop SDK in PHP

### ISSUE THREAD

**Issue by ghost** [HydroBlockchain/hcdp#208]
**What is the development you want done?**
[Raindrop](https://www.hydrogenplatform.com/docs/hydro/v1/#Raindrop) is a pair of authentication protocols developed by Hydrogen. This bounty is to create a PHP SDK for the Hydro Raindrop API.

**What are the deliverables?**
A fully functional SDK for the Hydro that meets or exceeds the functional standards of the existing [Javascript](https://github.com/hydrogen-dev/raindrop-sdk-js) and [Python](https://github.com/hydrogen-dev/raindrop-sdk-python) SDKs.

**Timeframe?**
We propose two weeks as the timeframe for completion of this task.

**Submission**
Due to migration from the previous HCDP format, this SDK has been claimed by @adrenth.

**Comment by adrenth** [comment]
Version 1.0.0 is available on packagist.

https://github.com/adrenth/raindrop-sdk

**Comment by ghost** [comment]
For the sake of consistency and fairness, we have increased this development bounty to 200,000 HYDRO, per previously distributed materials. Going forward, all bounty amounts (for SDKs and otherwise) will be determined according to the expected difficulty of the project.

**Comment by ghost** [comment]
This task has been successfully completed! The token transfer is visible here: https://etherscan.io/tx/0xd49252811742613ccc2222595b2b3a813bc3d4e181409210004f2f09084528b5.
