### ISSUE TITLE
CLAIMED 200,000 HYDRO to build a Raindrop SDK in Java

### ISSUE THREAD

**Issue by ghost** [HydroBlockchain/hcdp#209]
**What is the development you want done?**
[Raindrop](https://www.hydrogenplatform.com/docs/hydro/v1/#Raindrop) is a pair of authentication protocols developed by Hydrogen. This bounty is to create a PHP SDK for the Hydro Raindrop API.

**What are the deliverables?**
A fully functional SDK for the Hydro that meets or exceeds the functional standards of the existing [Javascript](https://github.com/hydrogen-dev/raindrop-sdk-js) and [Python](https://github.com/hydrogen-dev/raindrop-sdk-python) SDKs.

**Timeframe?**
We propose two weeks as the timeframe for completion of this task.

**Submission**
Due to migration from the previous HCDP format, this SDK has been claimed by @serkanalgl.

**Comment by ghost** [comment]
For the sake of consistency and fairness, we have increased this development bounty to 200,000 HYDRO, per previously distributed materials. Going forward, all bounty amounts (for SDKs and otherwise) will be determined according to the expected difficulty of the project.

**Comment by ghost** [comment]
@serkanalgl are you ready for this SDK to be reviewed by our team for completeness?

**Comment by serkanalgl** [comment]
@NoahHydro has not been published on maven central. If it is not a problem for your team, please feel free to review it. Actually, I'll release it and publish on maven central if tests have been passed successfully.

**Comment by ghost** [comment]
@serkanalgl we'll manually install and do some tests on our end. if everything looks good, then you can upload to maven and we'll send over the tokens! we'll get back to you by tomorrow or monday at the latest :)

EDIT: this has been delayed because of the Flatiron steam pipe explosion, we'll get to it ASAP @serkanalgl

**Comment by serkanalgl** [comment]
thank you :)

**Comment by ghost** [comment]
@serkanalgl, we've sent over an email detailing a few small fixes that need to be made, once those are addressed we will close out this bounty! Great work on this SDK.

**Comment by ghost** [comment]
Tokens were sent: https://etherscan.io/tx/0x2e69a09b8336da41a1745e84e077f68e5226a8b4749e5298cef182ecdb3517af

SDK is available at https://mvnrepository.com/artifact/com.github.serkanalgl/hydro-oauth2-java

**Comment by serkanalgl** [comment]
available on maven central:
https://mvnrepository.com/artifact/com.github.serkanalgl/hydro-raindrop-java/1.0.0

**Comment by adrenth** [comment]
Great job!
