### ISSUE TITLE
CLAIMED: 400,000 HYDRO to build a Passport.js module

### ISSUE THREAD

**Issue by ghost** [HydroBlockchain/hcdp#211]
**What is the development you want done?**

[Client Raindrop](https://github.com/hydrogen-dev/hydro-docs/tree/master/Raindrop) is a multi-factor authentication (MFA) protocol developed by Hydrogen. As part of the protocol, the Hydro mobile app generates HydroIDs for users to connect them to the forthcoming ecosystem of Hydro smart contracts, and serves as a secure keystore for users of the protocol.

This bounty is intended to foster broader adoption of Client Raindrop and the Hydro mobile app by offering developers tools to easily integrate Hydro MFA into their websites, APIs, and other projects. Specifically, the task is to create a [Passport.js](http://www.passportjs.org) module that provides a seamless implementation of the Client Raindrop MFA workflow. [Passport.js](http://www.passportjs.org) is a tool that allows developers to easily integrate authentication frameworks into [Express](https://expressjs.com/)-based web applications.

**What are the deliverables?**

A [Passport.js](http://www.passportjs.org) module implementing the Client Raindrop process. For detailed information on this process, see the [Hydro API documentation](https://www.hydrogenplatform.com/docs/hydro/v1/#Client-side). Our [implementation guide](https://medium.com/hydrogen-api/client-side-raindrop-an-implementation-guide-4e61c84e9dda) may be helpful as background information. Calls to the Hydro API should be made through the official [Javascript SDK](https://github.com/hydrogen-dev/raindrop-sdk-js).

Our intent is for this module to be oriented toward login-style, session-based authentication. For example we expect that HydroIDs will be garnered from session data. This is up for debate however, and we are more than happy to discuss the options. Regardless, a thorough justification for the ultimate implementation will be expected.

This module should have sufficient flexibility to be added as an [authorization layer](http://www.passportjs.org/docs/authorize/) after one or more successful authorizations.

Developers may complete this module per their preference, but a suggested approach is to mimic the [passport-totp](https://github.com/jaredhanson/passport-totp) implementation. A working and well-documented example with best-practice code should be provided.

**Timeframe?**

We propose one month as the timeframe for completion of this task.

**Submission process?**

First, comment on this issue to declare your willingness to complete the task.

Next, send us an email at noah@hydrogenplatform.com with:
- A link to your Github profile
- A link to a Javascript project in which you were the solo/a primary developer
- A paragraph explaining your understanding of Express, middleware, and how Raindrop fits in to this framework

We will evaluate applications factoring in these answers, Github activity, and the order in which you expressed interest. If you are selected, you will have one month to complete the task. During this time, we will be able to provide some support around questions about the workflow on Discord. If the task is not completed within the timeframe, we reserve the right to offer an extension or transfer the task to another candidate. Once the task is completed, we will test the module. If it is approved, we will then send you 400,000 HYDRO tokens.

**Comment by Red-Maximus** [comment]
I'm interested in tackling this. Been looking for a blockchain-related project and this seems up my alley. But, I'll look over the documentation thoroughly and confirm via email later.

**Comment by serkanalgl** [comment]
I'm interested to do this module. I sent you an email.

**Comment by cyphercodes96** [comment]
Highly interested

**Comment by dtq7** [comment]
Yes I'm interested.

**Comment by burhank6161** [comment]
Yes I'm interested.

**Comment by burhank6161** [comment]
for quick kyc approval
snowflake database loading of all countries' identity samples

**Comment by ghost** [comment]
Hi all, thanks for the interest. After consideration, we're going to reserve this bounty for @Red-Maximus! For those who were not selected, check back soon for additional bounties.

@Red-Maximus, feel free to post updates/discussion points in this thread or reach out on Discord. Good luck, and looking forward to seeing what you come up with. As a reminder, the target completion date is 8/27/2018.

**Comment by serkanalgl** [comment]
Good luck :)

**Comment by anklunk** [comment]
Yes i'm interested

**Comment by CryptopeX** [comment]
Yeah im interested 😍😍

**Comment by mabed-a** [comment]
Yes i'm interested

**Comment by ghost** [comment]
This task was completed successfully by @Red-Maximus and is [available here](https://github.com/Red-Maximus/passport-raindrop). Congrats!

[Proof of token send](https://etherscan.io/tx/0x39dcb4b78e9cbf2967d53fbbf7e26db5dcefbbd6ef44215dd5cd25009c4b7dcf).

**Comment by ghost** [comment]
Per off-Github discussion, the bounty for this issue was increased to 500,000 given bounty amount adjustments around the time of assignment.

[An additional 100,000 tokens were sent](https://etherscan.io/tx/0xad11932a322c152f7d4f78d0cd2eda019be24157b77d6fa469a195570683b033).
