### ISSUE TITLE
CLAIMED 25,000 HYDRO to build a Raindrop SDK in ColdFusion

### ISSUE THREAD

**Issue by ghost** [HydroBlockchain/hcdp#212]
**What is the development you want done?**
[Raindrop](https://www.hydrogenplatform.com/docs/hydro/v1/#Raindrop) is a pair of authentication protocols developed by Hydrogen. This bounty is to create a PHP SDK for the Hydro Raindrop API.

**What are the deliverables?**
A fully functional SDK for the Hydro that meets or exceeds the functional standards of the existing [Javascript](https://github.com/hydrogen-dev/raindrop-sdk-js) and [Python](https://github.com/hydrogen-dev/raindrop-sdk-python) SDKs.

**Timeframe?**
We propose two weeks as the timeframe for completion of this task.

**Submission**
This bounty has been claimed by @brett91ag per #207.

**Comment by ghost** [comment]
@brett91ag, let us know if the above is satisfactory. Do you have API keys to test your SDK in our Sandbox environment?

**Comment by brett91ag** [comment]
Thank you, I appreciate it.  Yes, I do have API keys and have tested it in the Sandbox.

**Comment by ghost** [comment]
Excellent! We'll do an internal review and get back to you shortly.

**Comment by ghost** [comment]
Ok @brett91ag, we got a chance to go over your code. The Server Raindrop portion looks good! Unfortunately, to be eligible for the bounty, you'll also need to implement wrapper functions for Client Raindrop API calls. The best reference for this will be the [Javascript SDK](https://github.com/hydrogen-dev/raindrop-sdk-js). Let us know if you have any questions/concerns.

**Comment by brett91ag** [comment]
Ok, might take some time.  I haven't had a look at the client API yet.

**Comment by anklunk** [comment]
Good luck..

**Comment by brett91ag** [comment]
Client-side Raindrop functions have been added.  Also, I created a demo application.   It has been verified to work with the Hydro app.

**Comment by anklunk** [comment]
Nice

**Comment by ghost** [comment]
This looks great @brett91ag! Could you reply with the Ethereum address you'd like to receive your bounty amount to?

**Comment by brett91ag** [comment]
0x696b43502F269C4dd33fd9d89D0fEa229eE57972

**Comment by ghost** [comment]
[Bounty sent](https://etherscan.io/tx/0x8f471082090c4407310eb85d9f72aebbb5711379f16bc8b941e28ea22d1ee15e). Thanks for the great work @brett91ag.

**Comment by brett91ag** [comment]
Was it sent to the wrong address?  looks like it went to 0xFE30578259e5454415654374ac86cd2F236281D7

**Comment by ghost** [comment]
Ahh, I fat-fingered it, that's one of our deployment addresses. [Updated proof](https://etherscan.io/tx/0xffbe769a502b677b42c1d2483507ed9647843ca05a6dcfb1fd836f3320ee6916). Sorry about that!

**Comment by brett91ag** [comment]
no problem, thank you!

**Comment by anklunk** [comment]
Good
