### ISSUE TITLE
450,000 HYDRO to perform a code review of the main Snowflake contract

### ISSUE THREAD

**Issue by shanehampton** [HydroBlockchain/hcdp#213]
**What is the development you want done?**
Snowflake is an identity management protocol. This task is to evaluate the current master state of the Solidity code in the [main Snowflake smart contract](https://github.com/hydrogen-dev/smart-contracts/blob/master/snowflake/contracts/Snowflake.sol), in order to identify any areas of potential improvement. Please review the [Snowflake white paper](https://github.com/hydrogen-dev/hydro-docs/blob/master/Snowflake/Snowflake_DRAFT.md) for more detailed information on the protocol.

**What are the deliverables?**
A thorough document detailing the code review. The document should contain, at minimum, the following sections:

1. _Overview_ - A summary of what you reviewed and the scope of your analysis.
2. _Methodology_ - Any pertinent information regarding techniques, tools, libraries, references, or frameworks leveraged during the code review process.
3. _Findings_ - Details on insights from the code review. Each finding consists of a category (`Security`, `Syntax`, `Extendability`, `Functionality`, `Gas Usage`, or `Other`), a description of the finding, relevant code location(s), severity (`Low`, `Medium`, or `High`), and a recommendation for potential improvement.

**Timeframe?**
We propose two weeks for this task.

**Submission process?**
First, comment on this issue to declare your willingness to complete the task. Next, send us an email at hydro@hydrogenplatform.com with a description of your tech background and qualifications (please include `HCDP Claim Request` somewhere in the email subject) . We will evaluate candidates factoring in these qualifications and the order in which they expressed interest. Once you have been selected, you will have two weeks to complete the task. During this time, the core Hydro team will be able to provide support on Discord regarding questions about the contract. If the task is not completed within the timeframe, we reserve the right to offer an extension or transfer the task to another candidate.

This task may be left open for successful submission from more than one contributor. Only submissions conveyed through GitHub will be officially considered.

**Comment by batux** [comment]
Hi,  I would like to review the project. If It is possible, I want to attend the bounty program.

**Comment by ramazan** [comment]
Hi,

I would like to review this project with enjoying.
I really excited for reviewing the project.

Best regards.

**Comment by ferdielik** [comment]
Hi, I would like to review to.

**Comment by cyphercodes96** [comment]
Highly interested

**Comment by MasterSensei** [comment]
For all those interested, please submit an email with your experience as noted in the guidelines. This will be assigned shortly. thanks!

**Comment by deoidh** [comment]
Interested!

**Comment by AnuragHydro** [comment]
@samgos thanks for the email - you are assigned for this task. The label on the task will remain "open request" because multiple developers are welcome to perform this task.

**Comment by clemlak** [comment]
I would like to review it too!

**Comment by AnuragHydro** [comment]
@clemlak you are also assigned for this task. The label on the task will remain "open request" because multiple developers are welcome to perform this task.

**Comment by AnuragHydro** [comment]
Task is temporarily closed as we make updates to the Snowflake Contract
