### ISSUE TITLE
750,000 Hydro to write a Hydro Token Dynamics Paper

### ISSUE THREAD

**Issue by AnuragHydro** [HydroBlockchain/hcdp#214]
**What is the task you want done?**
HYDRO Token Dynamics paper. Token Dynamics in the Hydro ecosystem are utilized in a variety of ways, sometimes with strict requirements, sometimes with arbitrary requirements as an expense for leveraging a network effect, and sometimes as a mechanism to make developing products on top of Hydro protocols easier. This task is for writing a detailed paper examining the current token structure, planning the token dynamics structure for future products, recommending changes within the current Hydro infrastructure, and assessing risks and mitigation strategies within the token economy. The focus of the paper should be on the underlying functionality of the token within the Hydro ecosystem as opposed to the market price or price trends of the token.

To aid in the completion of this task, you should reference [Hydro product whitepapers](https://github.com/hydrogen-dev/hydro-docs) and available resources and material about [Hydro token dynamics](https://medium.com/hydrogen-api/examining-hydro-token-dynamics-da68979cfc92) and are free to communicate with the core Hydro team with any questions.

**What are the deliverables?**
A detailed paper (3-7 page recommended length) that covers the aforementioned requirements. An ideal candidate will have a strong background in microeconomics and game theory. The selected candidate will need to regularly check in with the core Hydro team regarding any product questions, and also to provide updates on deliverables. The paper should be converted to markdown format and included in the [Hydro docs repo](https://github.com/hydrogen-dev/hydro-docs)

**Topics to consider including:**
- Background on token economics
- Examination of other token ecosystems - pros and cons of each
- M0 money supply economics
- Game structure and Economics of Staking
- Token burning economics
- Hydro 11.11 Bil Supply Explanation
- Raindrop Token Economics
- Snowflake Token Economics
- Ice Token Economics
- Tide Token Economics (consult team with questions once selected)
- Mist Token Economics (consult team with questions once selected)
- Decentralization Plan Economics (consult team with questions once selected)
- Business Usage Economics (consult team with questions once selected)
- Consumer App Economics (consult team with questions once selected)

**Timeframe?**
We propose two weeks as the time frame for completion of this task. The task will be considered complete when a sufficiently detailed paper is published in the appropriate repository, covering the aforementioned scope.

**Submission process?**
First, comment on this issue to declare your willingness to complete the task. Next, send us an email at hydro@hydrogenplatform.com with a description of your tech background and qualifications (please include HCDP Claim Request somewhere in the email subject) . We will evaluate candidates factoring in these qualifications and the order in which they expressed interest. Please provide us with examples of writing you have published similar in scope to the requested task. Once you have been selected, you will have two weeks to complete the task. During this time, the core Hydro team will be able to provide support on Discord regarding questions about the token model. If the task is not completed within the timeframe, we reserve the right to offer an extension or transfer the task to another candidate.

**Comment by NoDevXD** [comment]
I think i can make this work for Hydro, ill send the email later today

**Comment by Lisandrosgr** [comment]
I've taken part in other hcdp like translation of the raindop white paper or content.
I think i can create a really good white paper.

**Comment by kberey** [comment]
I can help when it comes in Filipino/Philippines white paper translation :)

**Comment by yahampathh** [comment]
I wish to help when it comes to Sinhala white paper translation!

**Comment by kberey** [comment]
I offer Tagalog/Philippines translation.

Please advise how and when.

Thanks,

**Comment by burhank6161** [comment]
???

**Comment by Jaylukmann** [comment]
I can deliver on this job,but l hope it is still on because Anurag opened this request 21 days ago and the time limit for the task is 2 weeks.

**Comment by AnuragHydro** [comment]
@Jaylukmann feel free to send us an email with any writing samples and information about your background :) Since we're looking for someone with a pretty extensive knowledge of game theory, we haven't yet filled the task; it's two weeks from when assigned, not posted.

**Comment by yahampathh** [comment]
Here I have attached my CV and samples.
Thank you!
Best Regards,
Yahampath

**Comment by Jaylukmann** [comment]
@yahampathh ,I can't find your attached CV and samples but will send the required mail to hydrogen@hydrogenplatform.com now.
Thanks

**Comment by Jaylukmann** [comment]
Good day @AnuragHydro,I am expecting your reply and approval on the hydro token dynamic paper

**Comment by AnuragHydro** [comment]
hi @Jaylukmann - we never received your email; the correct email address is hydro@hydrogenplatform.com - @yahampathh - same thing; we never received your email. Please send directly to hydro@hydrogenplatform.com with [HCDP claim request] somewhere in the subject line, per the submission instructions.

**Comment by dkswag** [comment]
I'm interested

**Comment by Uzobankz** [comment]
I'm willing & available to take on this job.

**Comment by Uzobankz** [comment]
@AnuragHydro I've written  token dynamic papers I can send over but me and my client signed NDA and he owns all credit and also can I send written white papers in place of samples?

**Comment by AnuragHydro** [comment]
@Uzobankz - sure that'd be great, can you send an email to hydro@hydrogenplatform.com? If you're unable to send us samples, could you send us some information about your background and the approach you intend to take?

**Comment by Uzobankz** [comment]
@AnuragHydro mail sent when should I expect a feedback?

**Comment by Jaylukmann** [comment]
Hi @AnuragHydro ,pls check  hydro@hydrogenplatform.com becauseI have sent the mail for the 2nd time.
Attached herewith is the screenshot of the reply I got from Michael Kane.
Or should I send it here on github
![screenshot_20180829-235127](https://user-images.githubusercontent.com/33833198/44820089-f4072b00-abde-11e8-830d-a72f69c554b0.png)

**Comment by Coinadz** [comment]
Hey Im interested if this project is still available. I got a technical background, have experience in writing papers and am a front end developer currently residing in Amsterdam. Cheers! Sent an email from bobbymetzijnhobby@gmail.com

**Comment by AnuragHydro** [comment]
Task is temporarily closed, as we build out components of TIDE that will affect the broader token economics of Project Hydro
