### ISSUE TITLE
800,000 HYDRO to build a Hydro Drupal Plug-in

### ISSUE THREAD

**Issue by AnuragHydro** [HydroBlockchain/hcdp#217]
**What is the development you want done?**
[Client Raindrop](https://github.com/hydrogen-dev/hydro-docs/tree/master/Raindrop) is a multi-factor authentication (MFA) protocol developed by Hydrogen. As part of the protocol, the Hydro mobile app generates HydroIDs for users to connect them to the forthcoming ecosystem of Hydro smart contracts. This bounty is intended to foster broader adoption of Client Raindrop and the Hydro mobile app by offering website administrators tools to easily integrate Hydro MFA into their sites. Specifically, this task is to create a [Drupal](https://www.drupal.org/) plug-in that integrates with the Hydro API to offer a seamless implementation of the MFA workflow.

**What are the deliverables?**

A Drupal plug-in implementing the Client Raindrop process. For detailed information on this process, see the [Hydro API documentation](https://www.hydrogenplatform.com/docs/hydro/v1/#Client-side). Our [implementation guide](https://medium.com/hydrogen-api/client-side-raindrop-an-implementation-guide-4e61c84e9dda) may be helpful as background information. Calls to the Hydro API should be made through an official Hydro SDK.

Our intent is for this module to be oriented toward login-style, session-based authentication. For example we expect that HydroIDs will be garnered from session data. This is up for debate however, and we are more than happy to discuss the options. Regardless, a thorough justification for the ultimate implementation will be expected.

This module should have sufficient flexibility to be added as an authorization layer after one or more successful authorizations.

Developers may complete this module per their preference, but a suggested approach is to reference the [Hydro wordpress plug-in](https://github.com/adrenth/wp-hydro-raindrop). A working and well-documented example with best-practice code should be provided.

**Timeframe?**
We propose one month as the timeframe for completion of this task.

**Submission process?**
First, comment on this issue to declare your willingness to complete the task. Next, fill out [the Drupal Plug-in Claim Form](https://docs.google.com/forms/d/e/1FAIpQLSe0QivIaiE8MK0VR_akmB40yHsGFHLHVMkWUrPTFH5HErrn9A/viewform?usp=sf_link). We will evaluate candidates factoring in their qualifications, Github activity, and the order in which they expressed interest. Once you have been selected, you will have one month to complete the task. During this time, we will be able to provide some support around questions about the workflow on [Discord](https://discordapp.com/invite/gxAUagw). If the task is not completed within the timeframe, we reserve the right to offer an extension or transfer the task to another candidate. Once the task is completed, we will test the plug-in for efficiency and whether or not it correctly incorporates the Hydro workflow. If we approve the plug-in, we will then send you 400,000 Hydro.

**Comment by adrenth** [comment]
Interested.

My idea is to make the plugin dependant of the already existing Hydro Raindrop PHP SDK package.

**Comment by blynn-dev** [comment]
Disappointed you took my idea for expanding your development ecosystem yet. Yet you didn’t accept me into your program as a DA.

**Comment by AnuragHydro** [comment]
@blynnXPO - sorry you feel like that's the case. We've been planning to roll out tasks for Drupal, Salesforce, nodeJS, shopify, etc. plugins since we originally created the wordpress plugin task. Once a Wordpress plugin already existed, extending that to plugins for ancillary softwares, especially one as similar as Drupal, is the natural course of action.

**Comment by proofoftom** [comment]
@AnuragHydro I'm interested in taking this on. I just submitted the Drupal Plug-In Claim form; look forward to hearing back!

**Comment by AnuragHydro** [comment]
Task assigned to @tommycox :) I'll reach out via email with further details

**Comment by AnuragHydro** [comment]
@tommycox we have been unable to reach you via email - could you send an email to anurag@hydrogenplatform.com?

**Comment by proofoftom** [comment]
Just replied. Have been swamped this week with SFBW, sorry!

**Comment by AnuragHydro** [comment]
Hi @tommycox - thanks for the github comment; did you send an email reply as well? didn't seem to come through. Can you try again? anurag@hydrogenplatform.com or da@hydrogenplatform.com

**Comment by HarshRajat** [comment]
Congrats @tommycox for completing the Drupal plugin. Please verify your ether address: 0x81aaA9a7a8358cC2971B9b8dE72aCCe6d7862BC8 by commenting below and your Hydro will be on it's way.

**Comment by proofoftom** [comment]
Confirmed, cheers! 🎉 🎊

**Comment by HarshRajat** [comment]
Task has been completed and bounty has been sent. Tx Hash: https://etherscan.io/tx/0x7534fc14f6e742ceaeab3b28d723d8c72b8c61fb0d0e45b99940e4b6556ff741
