### ISSUE TITLE
450,000 HYDRO to perform a code review of the DA Program smart contract

### ISSUE THREAD

**Issue by shanehampton** [HydroBlockchain/hcdp#218]
**What is the development you want done?**
The [Decentralized Ambassador (DA) Program](https://medium.com/hydrogen-api/become-a-hydro-decentralization-ambassador-da-d9ebf956d0c2) is an initiative to more heavily involve the Hydro community in the ongoing decentralization and global expansion of the Hydro blockchain ecosystem. This task is to evaluate the current master state of the Solidity code in the [DA Program smart contract](https://github.com/hydrogen-dev/smart-contracts/blob/master/decentralization-ambassadors/DA.sol), in order to identify any areas of potential improvement.

**What are the deliverables?**
A thorough document detailing the code review. The document should contain, at minimum, the following sections:

1. _Overview_ - A summary of what you reviewed and the scope of your analysis.
2. _Methodology_ - Any pertinent information regarding techniques, tools, libraries, references, or frameworks leveraged during the code review process.
3. _Findings_ - Details on insights from the code review. Each finding consists of a category (`Security`, `Syntax`, `Extendability`, `Functionality`, `Gas Usage`, or `Other`), a description of the finding, relevant code location(s), severity (`Low`, `Medium`, or `High`), and a recommendation for potential improvement.

**Timeframe?**
We propose two weeks for this task.

**Submission process?**
First, comment on this issue to declare your willingness to complete the task. Next, send us an email at hydro@hydrogenplatform.com with a description of your tech background and qualifications (please include `HCDP Claim Request` somewhere in the email subject) . We will evaluate candidates factoring in these qualifications and the order in which they expressed interest. Once you have been selected, you will have two weeks to complete the task. During this time, the core Hydro team will be able to provide support on Discord regarding questions about the contract. If the task is not completed within the timeframe, we reserve the right to offer an extension or transfer the task to another candidate.

This task may be left open for successful submission from more than one contributor. Only submissions conveyed through GitHub will be officially considered.

**Comment by cyphercodes96** [comment]
Interested

**Comment by clemlak** [comment]
I'm interested!

**Comment by AnuragHydro** [comment]
@clemlak - awesome! could you send an email to hydro@hydrogenplatform.com with a description of your tech background and qualifications with `HCDP Claim Request` in the subject line of the email?

**Comment by clemlak** [comment]
Sure :)

**Comment by AnuragHydro** [comment]
@clemlak has been marked down as `claimed` for this task. We are keeping the label as `open request` because this task can be completed by multiple people.

**Comment by cyphercodes96** [comment]
@AnuragHydro huge distinction occurring in picking contributors amongst your community members.
Although I am one of the earliest supporters of hydro, and hold huge enthusiasm to join and help.
I was never assigned to any HDCP ticket.
Y'all got me blacklisted for some reason...

**Comment by AnuragHydro** [comment]
@cyphercodes96 - never got your email with "HCDP Claim Request" in the subject line for this task as outlined in the "submission process" section

**Comment by deoidh** [comment]
Interested in partaking.

**Comment by AnuragHydro** [comment]
@samgos thanks for the email - you are assigned for this task. The label on the task will remain "open request" because multiple developers are welcome to perform this task.

**Comment by ghost** [comment]
Thanks to @clemlak and @samgos for their excellent work reviewing the Hydro DA smart contract! We'll be incorporating the results of their audits into the code, and plan to release a live version of the smart contract in the coming weeks.

[Tokens were sent](https://etherscan.io/tx/0x64703612480f77fd1d4a524226638e9f6ae2f81dc0152ad6f5658555a2317da1) to @clemlak.
[Tokens were sent](https://etherscan.io/tx/0xa638103c1254667417d16bea8eb1442498028003e9f5e4564156a5e222bd09f9) to @samgos.
