### ISSUE TITLE
700,000 HYDRO to build a Hydro Joomla Plug-in

### ISSUE THREAD

**Issue by AnuragHydro** [HydroBlockchain/hcdp#219]
What is the development you want done?
[Client Raindrop](https://github.com/hydrogen-dev/hydro-docs/tree/master/Raindrop) is a multi-factor authentication (MFA) protocol developed by Hydrogen. As part of the protocol, the Hydro mobile app generates HydroIDs for users to connect them to the forthcoming ecosystem of Hydro smart contracts. This bounty is intended to foster broader adoption of Client Raindrop and the Hydro mobile app by offering website administrators tools to easily integrate Hydro MFA into their sites. Specifically, this task is to create a [Joomla](https://www.joomla.org/) plug-in that integrates with the Hydro API to offer a seamless implementation of the MFA workflow.

What are the deliverables?

A Joomla plug-in implementing the Client Raindrop process. For detailed information on this process, see the [Hydro API documentation](https://www.hydrogenplatform.com/docs/hydro/v1/#Client-side). Our [implementation guide](https://medium.com/hydrogen-api/client-side-raindrop-an-implementation-guide-4e61c84e9dda) may be helpful as background information. Calls to the Hydro API should be made through the official [Hydro PHP SDK](https://github.com/adrenth/raindrop-sdk).

Our intent is for this module to be oriented toward login-style, session-based authentication. For example we expect that HydroIDs will be garnered from session data. This is up for debate however, and we are more than happy to discuss the options. Regardless, a thorough justification for the ultimate implementation will be expected.

This module should have sufficient flexibility to be added as an authorization layer after one or more successful authorizations.

Developers may complete this module per their preference, but a suggested approach is to reference the [Hydro wordpress plug-in](https://github.com/adrenth/wp-hydro-raindrop). A working and well-documented example with best-practice code should be provided. The completed result should enable Joomla websites and custom implementations of Joomla websites to easily integrate Hydro 2FA into their sites.

Timeframe?
We propose one month as the timeframe for completion of this task.

Submission process?
First, comment on this issue to declare your willingness to complete the task. Next, fill out the [Joomla Plug-in Claim Form](https://goo.gl/forms/gP00j92AlUfmoHfz1). We will evaluate candidates factoring in their qualifications, Github activity, and the order in which they expressed interest. Once you have been selected, you will have one month to complete the task. During this time, we will be able to provide some support around questions about the workflow on Discord. If the task is not completed within the timeframe, we reserve the right to offer an extension or transfer the task to another candidate. Once the task is completed, we will test the plug-in for efficiency and whether or not it correctly incorporates the Hydro workflow. If we approve the plug-in, we will then send you 700,000 Hydro.

**Comment by realquink** [comment]
Hey Anurag, It's "jhall2017" from Discord. I am interested in doing this Joomla plugin. Thanks

**Comment by cyphercodes96** [comment]
Interested

**Comment by AnuragHydro** [comment]
Task is approved for @realquink

**Comment by AnuragHydro** [comment]
@mitdralla will be receiving 200,000 HYDRO for overseeing/supervising the completion of this task.

**Comment by ghost** [comment]
This task has been successfully completed! Congrats to @realquink @DaveM2011 and @mitdralla. The plugin will be available soon on the [Joomla Store](https://extensions.joomla.org/index.php?option=com_jed&view=extension&layout=default&id=14133&Itemid=145), and the code is available [on Github](https://github.com/DaveM2011/joomla-hydro-raindrop).

[Tokens sent](https://etherscan.io/tx/0x9833516cc9df90a5378ea44bc78858d4a1224e5191693d060b98a04af382f2c8) to @mitdralla.
[Tokens sent](https://etherscan.io/tx/0x164eb52a1640c14c1a55e8b8088bc5bd9a16ec06959d10f991f6b5a70767f68a) to @realquink and @DaveM2011.

**Comment by adrenth** [comment]
Great job guys!

**Comment by realquink** [comment]
Thanks @adrenth and thanks for pioneering this with the WordPress plugin!

**Comment by HarshRajat** [comment]
Awesome! Tim told us about the great team work and brain storming which
happened for this plugin! Hats off to all of you.

**Comment by mitdralla** [comment]
Yes, piggy backing off of @HarshRajat, great work team!

**Comment by MasterSensei** [comment]
Hi @realquink @DaveM2011 and @mitdralla. We received a message from Joomla saying they rejected the extension because Hydrogen is a paid service. They are mistaken. This extension is for Hydro, which is 100% free all the time, not freemium, or pay as you go. They said 'Please open a ticket under “New Listing Support” and ask for it to be checked again."

**Comment by mitdralla** [comment]
@MasterSensei - ticket submitted, stay tuned.
