### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by vominhtri1611** [HydroBlockchain/hcdp#22]
**Link to the posted content**
https://medium.com/@vminhtr_42068/hydro-potential-project-and-the-future-of-2fa-apps-e7bf99948968
**Ethereum Address**
0x217714E72cAaa62f2C6A1C80e154eB05Af1F52E6

**Comment by ghost** [comment]
We are no longer accepting content submissions as part of the HCDP. Thank you for your submission.
