### ISSUE TITLE
800,000 HYDRO to build a Hydro Salesforce Plug-in

### ISSUE THREAD

**Issue by AnuragHydro** [HydroBlockchain/hcdp#220]
What is the development you want done?
[Client Raindrop](https://github.com/hydrogen-dev/hydro-docs/tree/master/Raindrop) is a multi-factor authentication (MFA) protocol developed by Hydrogen. As part of the protocol, the Hydro mobile app generates HydroIDs for users to connect them to the forthcoming ecosystem of Hydro smart contracts. This bounty is intended to foster broader adoption of Client Raindrop and the Hydro mobile app by offering website administrators tools to easily integrate Hydro MFA into their sites. Specifically, this task is to create a [Salesforce](https://www.salesforce.com/form/sem/salesforce.jsp?gclid=EAIaIQobChMIyPLLzYrt3AIVhUSGCh0gCwS5EAAYASAAEgIajvD_BwE&d=70130000002IBwu&nc=7010M000002MJQ0&DCMP=KNC-Google&s_kwcid=AL!4604!3!79359516899!e!!g!!salesforce&ef_id=Wun8JAAAAL23NVdN:20180814173726:s) plug-in that integrates with the Hydro API to offer a seamless implementation of the MFA workflow.

What are the deliverables?

A Salesforce plug-in implementing the Client Raindrop process. For detailed information on this process, see the [Hydro API documentation](https://www.hydrogenplatform.com/docs/hydro/v1/#Client-side). Our [implementation guide](https://medium.com/hydrogen-api/client-side-raindrop-an-implementation-guide-4e61c84e9dda) may be helpful as background information. Calls to the Hydro API should be made through an official Hydro SDK.

Our intent is for this module to be oriented toward login-style, session-based authentication. For example we expect that HydroIDs will be garnered from session data. This is up for debate however, and we are more than happy to discuss the options. Regardless, a thorough justification for the ultimate implementation will be expected.

This module should have sufficient flexibility to be added as an authorization layer after one or more successful authorizations.

Developers may complete this module per their preference, but a suggested approach is to reference the [Hydro wordpress plug-in](https://github.com/adrenth/wp-hydro-raindrop). A working and well-documented example with best-practice code should be provided. The completed result should enable Salesforce websites and custom implementations of Salesforce websites to easily integrate Hydro 2FA into their sites.

Timeframe?
We propose one month as the timeframe for completion of this task.

Submission process?
First, comment on this issue to declare your willingness to complete the task. Next, fill out the [Salesforce Plug-in Claim Form](https://docs.google.com/forms/d/e/1FAIpQLSdnlCwbDJLQSN4r6DTnc1pNm_wF7U1IdvBJvcJTj111BX7m7A/viewform?usp=sf_link). We will evaluate candidates factoring in their qualifications, Github activity, and the order in which they expressed interest. Once you have been selected, you will have one month to complete the task. During this time, we will be able to provide some support around questions about the workflow on [Discord](https://discordapp.com/invite/gxAUagw). If the task is not completed within the timeframe, we reserve the right to offer an extension or transfer the task to another candidate. Once the task is completed, we will test the plug-in for efficiency and whether or not it correctly incorporates the Hydro workflow. If we approve the plug-in, we will then send you 800,000 Hydro.

**Comment by brett91ag** [comment]
I am interested in this task.

**Comment by paul2688** [comment]
I am interested in this task.

**Comment by sheikktj** [comment]
Good

**Comment by cyphercodes96** [comment]
Interested

**Comment by paul2688** [comment]
I am interested in this task.
Unlike other 2FA, HYDRO offers great dual security through interesting applications.

**Comment by vanphandinh** [comment]
looks fantastic.

**Comment by AnuragHydro** [comment]
Task assigned to @brett91ag

**Comment by HoLyDreaM** [comment]
I am interested in this task.
