### ISSUE TITLE
600,000 HYDRO to create a Snowflake Identicon Generator

### ISSUE THREAD

**Issue by AnuragHydro** [HydroBlockchain/hcdp#221]
**What is the development you want done?**
This task is for an aesthetic Identicon Generator that dApp developers can leverage when using the snowflake protocol. Since each snowflake is owned by a unique public address, a sophisticated design framework would create a standard, unique, familiar user icon associated with their snowflake, leveraging unique design elements for each possible alphanumeric character at each position across the 40 hex characters of the public address. The process would be similar to what is used in [blockies](https://github.com/ethereum/blockies). 

**What are the deliverables?**
A Javascript package that generates a unique visual representation of every possible snowflake for each user based on the public address. This requires both design work and development work.

**Timeframe?**
We propose one month for the completion of this task.

**Submission process?**
Please comment on this issue declaring your willingness to complete the task and fill out [this questionnaire](https://docs.google.com/forms/d/e/1FAIpQLScCNm5ljnWfrSgL8SINsy8_E8d7UZpT6zYGfgeg0blwaftN6g/viewform). If we approve your claim for the task, someone from the team will reach out to you and indicate as such on this issue. We will evaluate candidates factoring in these qualifications, Github activity, and the order in which they expressed interest. Once you have been selected, you will have one month to complete the task. During this time, we will be able to provide some support around questions about the workflow on [Discord](https://discordapp.com/invite/gxAUagw). If the task is not completed within the timeframe, we reserve the right to offer an extension or transfer the task to another candidate. Once the task is completed, we will test the generator. If we approve it, we will then send you 600,000 Hydro.

**Comment by cyphercodes96** [comment]
Interested

**Comment by paul2688** [comment]
Interested.
sophisticated design in this regard is indeed needed. because in modern times now the competition between one another is very strict.

**Comment by Amirh24** [comment]
So something similar to this?
http://www.monkeygen.com

**Comment by AnuragHydro** [comment]
yes, exactly @Amirh24 ! 

@cyphercodes96  is currently working on this task; I'll keep updates coming on this thread.

**Comment by Amirh24** [comment]
I actually created the monKey concept and wrote about it here:
https://hackernoon.com/gamifying-crypto-the-benefits-of-personalized-avatars-a74f40e6ae89
Great to see other projects taking this approach, good luck!

**Comment by AnuragHydro** [comment]
@Amirh24 that was a great article! We're really excited to see what @cyphercodes96 puts together and are planning to integrate it into the [dashboard](https://github.com/NoahHydro/snowflake-dashboard) we're building out. You should hop on our [Discord](https://discordapp.com/invite/gxAUagw) so we can stay in touch!

**Comment by AnuragHydro** [comment]
@Amirh24 will take an oversight role for this task. 300,000 additional tokens will be disbursed to him for his assistance in this capacity.

**Comment by cyphercodes96** [comment]
This task is `done`.
Final package repository below:
https://github.com/cyphercodes96/Hydro-Snowflake-Identicon-Generator

**Comment by AnuragHydro** [comment]
Tokens sent to @cyphercodes96 and @Amirh24 respectively:

https://etherscan.io/tx/0x1642c3bbe6d522c8dd2dc7263bc7b4272f3930a504d2e2580878fd0d0f5854ea

https://etherscan.io/tx/0xc959967bc05dfd4aef410d2e2a80bca1d7b6667b7a26b957cb5e6beab948c716
