### ISSUE TITLE
500,000 Hydro to extend the Hydro Wordpress Plug-in

### ISSUE THREAD

**Issue by AnuragHydro** [HydroBlockchain/hcdp#223]
**Preference for this task will be given to @adrenth who completed the initial task for the Wordpress Plugin.**

**What is the development you want done?**
The current [Hydro Wordpress plug-in](https://github.com/adrenth/wp-hydro-raindrop) is optimized for websites that use the wordpress UI; however, many website developers using wordpress have custom implementations with their own code and UI. 
The task is to add hooks to the existing wordpress plug-in that custom sites built on wordpress can use to implement the Hydro 2fa workflow into their own UIs as well as to add some additional admin functions into the plugin.

**What are the deliverables?**
Researching how other popular plugins provide capabilities for their users to integrate the plugin into custom front-ends. Pick a strategy that will allow the Wordpress plugin to expose its functionality so that sites built with their own UI on top of Wordpress can modify their UI while still replicating the 2FA flow created by the plugin as it stands.

Additionally, site managers may want to restrict certain screens (or their entire site) to users who have implemented Hydro 2FA. The second deliverable for this task is to add functionality that allows site admins to chedk whether a logged-in user has 2FA enabled, so that certain screens can be restricted based on whether or not the 2FA is enabled.

**Timeframe?**
We propose 2 weeks for the completion of this task.

**Submission process?**
This task is reserved for @adrenth, as it is an extension of his own code. 

**Oversight Process**
@harshrajat will be overseeing the completion of this task outside the scope of his role as a DA. He will claim a 100,000 Hydro bounty for his assistance in this role.

**Comment by adrenth** [comment]
Anyone who's interested can follow the development of the WordPress plugin here:
https://github.com/adrenth/wp-hydro-raindrop

**Comment by adrenth** [comment]
V1.3 contains the deliverables mentioned in this issue. 

Plugin can be found at https://wordpress.org/plugins/wp-hydro-raindrop/

Users can install the plugin within Plugin-section of their WordPress site.

**Comment by NoahZinsmeister** [comment]
This task has been completed successfully!

https://etherscan.io/tx/0xe9014233fc58c530e735bb25fd4a7f7e080ba7817362935b21e38444905f1e75
https://etherscan.io/tx/0x92cd38c6466a90fa530ca009ab4f1b9fcf519560d551e89673cb1ad7ec082e42

**Comment by AnuragHydro** [comment]
Thanks everyone!
