### ISSUE TITLE
**Designer wanted** 600,000 HYDRO to design Snowflake Identicon Generator

### ISSUE THREAD

**Issue by AnuragHydro** [HydroBlockchain/hcdp#226]
**What is the development you want done?**
This task is the design component of the [Snowflake Identicon Generator](https://github.com/hydrogen-dev/hcdp/issues/221) task. We are aiming to create unique, visually appealing avatars tied to a user's public address. [monKey](https://hackernoon.com/gamifying-crypto-the-benefits-of-personalized-avatars-a74f40e6ae89) is a great example. 

**What are the deliverables?**
Details to be discussed in [Discord](https://discordapp.com/invite/gxAUagw) - the general principle is to create unique Snowflake avatars for each member of the Hydro ecosystem.

**Timeframe?**
We propose three weeks - working in conjunction with the developer who has claimed the development portion of this task.

**Submission process?**
Please comment on this issue declaring your willingness to complete the task and fill out [this questionnaire](https://docs.google.com/forms/d/e/1FAIpQLSciQSHEf1Zmf5iZ4RWDyIfqMT5Xa3aKeItM3GIn7sD7O5lslg/viewform?usp=sf_link). If we approve your claim for the task, someone from the team will reach out to you and indicate as such on this issue. We will evaluate candidates factoring in these qualifications, Github activity, and the order in which they expressed interest. Once you have been selected, you will have one month to complete the task. During this time, we will be able to provide some support around questions about the workflow on Discord. If the task is not completed within the timeframe, we reserve the right to offer an extension or transfer the task to another candidate. Once the task is completed, we will test the generator. If we approve it, we will then send you 600,000 Hydro.

**Comment by realquink** [comment]
Is this just to design just the Avatar portion or is to design the avatar and the website UI/UX (interface) that the avatars will be used on?

**Comment by AnuragHydro** [comment]
Avatar portion; it should be plug-and-play usable by websites.

**Comment by Dikolash** [comment]
![snowflake_pinguin_2](https://user-images.githubusercontent.com/24544133/44801427-b5af4300-abc1-11e8-9277-116ba3276111.gif)

**Comment by codemathics** [comment]
I am interested in this task, would be a privilege to be given a chance. Thanks!

**Comment by ivan2805** [comment]
How to apply for this? I'm interested

**Comment by puppetbrain** [comment]
I'm interested and have just filled out the form.

**Comment by AnuragHydro** [comment]
Task is approved for @puppetbrain based on form responses. Thank you to all who filled out the form!

**Comment by AnuragHydro** [comment]
Task is completed. Tx hash: https://etherscan.io/tx/0xf341ebef90e1c36f66e878405ec55a7aebfb1466ab5566b6d081a32c8ae7a645

See issue #221 for further details
