### ISSUE TITLE
800,000 HYDRO to create a shopify plug-in 

### ISSUE THREAD

**Issue by AnuragHydro** [HydroBlockchain/hcdp#227]
Shopify plugin

**What is the development you want done?**

[Client Raindrop](https://github.com/hydrogen-dev/hydro-docs/tree/master/Raindrop) is a multi-factor authentication (MFA) protocol developed by Hydrogen. As part of the protocol, the Hydro mobile app generates HydroIDs for users to connect them to the forthcoming ecosystem of Hydro smart contracts. This bounty is intended to foster broader adoption of Client Raindrop and the Hydro mobile app by offering website administrators tools to easily integrate Hydro MFA into their sites. Specifically, this task is to create a [Shopify](https://www.shopify.com/) plug-in that integrates with the Hydro API to offer a seamless implementation of the MFA workflow. The reason for this plug-in is to streamline the mechanism by which e-commerce sites can provide MFA security.

**What are the deliverables?**

A Shopify plug-in implementing the Client Raindrop process. For detailed information on this process, see the [Hydro API documentation](https://www.hydrogenplatform.com/docs/hydro/v1/#Client-side). Our implementation guide may be helpful as background information. Calls to the Hydro API should be made through an official Hydro SDK such as the [PHP](https://github.com/adrenth/raindrop-sdk), [Java](https://github.com/serkanalgl/hydro-raindrop-java), [JavaScript](https://github.com/hydrogen-dev/raindrop-sdk-js), or [Python](https://github.com/hydrogen-dev/raindrop-sdk-python) SDK.
Our intent is for this module to be oriented toward login-style, session-based authentication. For example we expect that HydroIDs will be garnered from session data. This is up for debate however, and we are more than happy to discuss the options. Regardless, a thorough justification for the ultimate implementation will be expected.
This module should have sufficient flexibility to be added as an authorization layer after one or more successful authorizations. Further, it must have sufficient flexibility to be utilized by businesses with custom pages built on Shopify.
Developers may complete this module per their preference, but a suggested approach is to reference the [Hydro wordpress plug-in](https://github.com/adrenth/wp-hydro-raindrop). A working and well-documented example with best-practice code should be provided. The completed result should enable Shopify websites and custom implementations of Shopify websites to easily integrate Hydro 2FA into their sites.

*To ensure consistency, the Plugin should follow the [Hydro Plug-in Architecture Guidelines](https://docs.google.com/document/d/1kyI5NFHi4kfzSJqWsFNAP71YNr9dsp0EugV8igJvlgU/edit)*

**Timeframe?**

We propose one month as the timeframe for completion of this task.

**Submission process?**

First, comment on this issue to declare your willingness to complete the task. Next, fill out the [Shopify Plug-in Claim Form](https://goo.gl/forms/nyAQTfh1qnGftlnF2). We will evaluate candidates factoring in their qualifications, Github activity, and the order in which they expressed interest. Once you have been selected, you will have one month to complete the task. During this time, we and Hydro DAs will be able to provide some support around questions about the workflow on [Discord](https://discordapp.com/invite/gxAUagw). If the task is not completed within the timeframe, we reserve the right to offer an extension or transfer the task to another candidate. Once the task is completed, we will test the plug-in for efficiency and whether or not it correctly incorporates the Hydro workflow. If we approve the plug-in, we will then send you 800,000 Hydro.

**Comment by Coinadz** [comment]
I am interested in completing this task, I am a front end developer with some API integration experience working with the OST development kit for the OST alpha. Cheers!

**Comment by cyphercodes96** [comment]
Why was the official PHP sdk chosen for this plugin?

Although shopify API could be easily used to interact with in any language (  .Net, Python, Ruby, PHP, Go, Javascript ) as long as we deal with the API properly.

**Comment by toogittoquit** [comment]
@cyphercodes96 Are you on Discord? You can ask in there why the devs put PHP as the suggested SDK. Thanks!

**Comment by cyphercodes96** [comment]
@toogittoquit Yes sure am.
Recently asked Anurag about this

**Comment by AnuragHydro** [comment]
Good point, description updated

**Comment by adrenth** [comment]
@cypercodes96 why should the community maintain multiple codebases for the same task? 

When the Hydro API changes, the community can provide updates to a central maintained “controlled” package. Instead of having al sort of plugins which have their own implementation of communicating with the API. Which I think is a bad practice.

**Comment by cyphercodes96** [comment]
@adrenth Honestly I don't see how that would matter, since the SDK's are already implemented and developed in different languages.
Also i see this as a bonus for us, this would help the Hydro community to diverse and have people from different communities

**Comment by cyphercodes96** [comment]
Interested, messaging @NoahHydro on discord

**Comment by MasterSensei** [comment]
What is status of this? Would be great to get a Shopify plugin before the Hydrogen team starts running targeted campaigns to e-commerce firms.

**Comment by cyphercodes96** [comment]
@MasterSensei been asking the team one by one about the status of this for the past month**.

I was asked to contact DA @HarshRajat.

His response was: `Sure, let me check on the status of the ticket and get back`
later on: `Hey Rawad! We are still finalizing a few things, will need me some more time to get back to you.`

**Comment by bartsimpson1000** [comment]
> @MasterSensei been asking the team one by one about the status of this for the past month**.
> 
> I was asked to contact DA @HarshRajat.
> 
> His response was: `Sure, let me check on the status of the ticket and get back`
> later on: `Hey Rawad! We are still finalizing a few things, will need me some more time to get back to you.`

ok, good to now this is moving forward! shopify is big for raindrop integrations, lots of demand in the community

**Comment by HarshRajat** [comment]
Closed since Shopify Requirements / Bounty is changed. Will post shortly.

**Comment by mitdralla** [comment]
Link to new bounty: https://github.com/HydroBlockchain/hcdp/issues/246
