### ISSUE TITLE
Translations BlockTank To Thai Language

### ISSUE THREAD

**Issue by niawjunior** [HydroBlockchain/hcdp#23]
Thai Language

0xcF4CA355eC55724DEC46404B360bC00E516f6E8F

https://medium.com/@njth/%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%81%E0%B8%B2%E0%B8%A8%E0%B8%AB%E0%B8%B2%E0%B8%9C%E0%B8%B9%E0%B9%89%E0%B9%80%E0%B8%82%E0%B9%89%E0%B8%B2%E0%B8%A3%E0%B9%88%E0%B8%A7%E0%B8%A1-block-tank-3a52bc87c11a

from this article
https://medium.com/hydrogen-api/announcing-blocktank-participants-3295ab792ad2

**Comment by AndyHydro** [comment]
Sorry we are not looking for medium article translations

**Comment by niawjunior** [comment]
sorry please check it again please https://bit.ly/2INmHG8
