### ISSUE TITLE
700,000 HYDRO for Snowflake Dashboard Redesign

### ISSUE THREAD

**Issue by AnuragHydro** [HydroBlockchain/hcdp#232]
**What is the development you want done?**
This task is for a designer or design team to redesign the [Snowflake web portal](https://noahhydro.github.io/snowflake-dashboard/) for an even more user-friendly, aesthetic, and Hydro brand-consistent appearance that preserves all of its functionality. 

The new design does not need to preserve the formatting or item-location of the below wireframes; they are presented in order to inform the designer of all of the necessary functionality that needs to be preserved and displayed to users. We also highly recommend reading our [product article](https://medium.com/hydrogen-api/snowflake-identity-protocol-and-the-hydro-dapp-store-61d8fadcce0f) about Snowflake for context as well as navigating the [current web portal](https://noahhydro.github.io/snowflake-dashboard/) to attain a hands-on grasp of the current functionality before starting the redesign. 

**What are the deliverables?**
Please view [this document](https://docs.google.com/document/d/1qxxck1NYMyoUPZ4Pr4qlfH-GQB7QdXg05Y98BDD97ZM/edit?usp=sharing) for a description of the deliverables

**Timeframe?**
We propose two weeks for the completion of this task

**Submission process?**
Please comment on this issue declaring your willingness to complete the task and fill out [this questionnaire](https://goo.gl/forms/3ikklUchuisc6Jl02). If we approve your claim for the task, someone from the team will reach out to you and indicate as such on this issue. We will evaluate candidates factoring in these qualifications, Github activity, and the order in which they expressed interest. Once you have been selected, you will have two weeks to complete the task. During this time, we will be able to provide some support around questions about the workflow on [Discord](https://discordapp.com/invite/qMFbNcS). If the task is not completed within the timeframe, we reserve the right to offer an extension or transfer the task to another candidate. Once the task is completed, we will test the generator. If we approve it, we will then send you 700,000 Hydro.

**Comment by Coinadz** [comment]
I am willing, hope to fullfill this one. Cheers

**Comment by realquink** [comment]
What would be the desired format for the design to be delivered in? PSD, JPG, etc?

Thanks

**Comment by sir46aj** [comment]
My team (@sofiaaifos, @munizzang) and I will be interested in taking on this project. :)

**Comment by realquink** [comment]
> What would be the desired format for the design to be delivered in? PSD, JPG, etc?
> 
> Thanks

I am interested in taking on this design project. Thanks

**Comment by puppetbrain** [comment]
Me and my partner @benzai are interested and have filled out the form. Seems like I can't put more than one link in the LinkedIn profile in the form so I only provided one LInkedIn and GitHub profile.

**Comment by puppetbrain** [comment]
My partner @benzai and I are interested and have filled out the form. Seems like I can't put more than one link in the LinkedIn profile in the form so I only provided one LInkedIn and GitHub profile.

**Comment by AnuragHydro** [comment]
Thanks to all who applied - really high quality applications from all! Ultimately, we decided to go with @sir46aj and team due to their extensive contributions to the designs of the Hydrogen website and Hydro mobile app. We and the Hydro DAs will certainly be posting more design-oriented tasks in the near future.

**Comment by AnuragHydro** [comment]
In discussion with @sir46aj and team, we have closed this issue, and Hydrogen will be completing the task for 0 tokens rather than HCDP
