### ISSUE TITLE
------

### ISSUE THREAD

**Issue by mitdralla** [HydroBlockchain/hcdp#238]

**Comment by PierrickGT** [comment]
Hi @HarshRajat,
As a front-end developer, how can I get involved in the development of this website?

**Comment by HarshRajat** [comment]
Hi @PierrickGT, My development and design agency is handling this so we are covered on this Task.

**Comment by PierrickGT** [comment]
Oh alright.

So Hydro isn't really an open source project if Github issues are handled by agencies no?

**Comment by HarshRajat** [comment]
There are a lot of HCDP tasks that are posted for all and some that have been reserved as has been in the past. I think it's best for me to refrain from this discussion since I am a part of this HCDP task.

**Comment by PierrickGT** [comment]
Most of the recent tasks are shared by you and @mitdralla.
As a Javascript Front-End Developer, there's only a few projects I can contribute too. This one seemed to be a good fit for me.
To me, it looks like you don't even ask for the community to apply for the different tasks, you just share projects between you two.

**Comment by mitdralla** [comment]
Hello @PierrickGT, thank you for your feedback. The HCDP Trello board has over 100 bounties as it stands right now, some of which are ready to be released as they align with current phases of Hydro - others will come out as the project progresses. 

Since the DA program started there have been some early initiatives and great ideas which have already began development and that is the reason those tasks are reserved, and in the interest of being completely transparent they have been posted just like any other bounty.

Each bounty on the list has to be defined, scoped out and looked at from a variety of angles. Will this add value to the program? What is a competitive and rewarding bounty total? Is the timeframe reasonable?  Who will be responsible for overseeing the project?

From there they are categorized and prioritized. The next step is to figure out who will be overseeing the project - this person needs to closely follow the development project, make sure best practices are being used, collaborate, quality check, ensure all requirements are met, and finally make sure payment has been sent.

Once things are ready to go, the final step is to determine a bounty total. We need to step back, look at the big picture, comb through the requirements and determine a competitive and rewarding value base on today’s price, not a future price. At that point it hits GitHub. 

You will see Harsh and I overseeing lot of those, because right now it has just been 2 DAs with engineering skills capable of that oversight on the DA team. At any given point, currently, we can be overseeing 3-4 projects, and as we roll out more bounties we will need to either take on more, or grow those overseers to more devs. 

We do not want to limit creativity on community members eager to contribute, because we know that building great things will continue to contribute to the projects success. 

Anyone can submit a bounty with defined requirements to grow the ecosystem, it will be looked at and assessed and if a valuable contribution is determined, bounty total assigned and paid out upon completion and deliverable handoff.

**Comment by PierrickGT** [comment]
Thank you very much for your answer ! It's way more clear now.
Where can I find the HDCP Trello board?

**Comment by realquink** [comment]
@mitdralla Is this the final design for the homepage of the future Hydro site? I'm hoping it's not as it seems like not much is on there. For example, only 1 phase is listed. I could assist in helping the design if needed. A recent example of adding more value to a homepage aesthetically and content-wise can be found here:

https://www.behance.net/gallery/71955487/BJU-Press-Site-Design-Before-and-After

BTW I'm not saying the design is bad either. I just believe it could be expanded upon. Just throwing it out there, not trying to step on anyone's toes :)

**Comment by HarshRajat** [comment]
Hi @realquink, Thanks for providing your valuable feedback, really appreciate it 👍. The above was just the start of the homepage design, the rest of it are getting worked out, for example: rain falling for raindrop phase, maybe more. for ice phase it's penguin, snowcapped mountains, icebergs, ice cubes,
and it being able to slide, mist might make it misty from below and so on and so forth. 

I am attaching the storyboard which we have come up earlier for the homepage, feel free to point out if something is missing or should be added... btw the storyboard just outlines the flow of the content and doesn't really emphasize on the visual aspect or layout of it, just as how the story would be presented. 
[wireframe_homepage.pdf](https://github.com/HydroCommunity/hcdp/files/2543864/wireframe_homepage.pdf)

**Comment by realquink** [comment]
@HarshRajat Awesome looks like you guys got it covered! The storyboard is more along the lines I was thinking. Looking forward to seeing it all done :)
