### ISSUE TITLE
800,000 Hydro to create OctoberCMS(Phase 1) Raindrop Plug-in

### ISSUE THREAD

**Issue by HarshRajat** [HydroBlockchain/hcdp#242]
The task is reserved for a developer who has contributed to the Hydro ecosystem and have completed various projects for us. They wish to remain anonymous for this task which is why we can’t disclose their name but if anyone wants to connect or vet them out then they can approach us on Discord and we will be happy to connect them to the developer.

**What is the development you want done?**

Client Raindrop is a multi-factor authentication (MFA) protocol developed by Hydrogen. As part of the protocol, the Hydro mobile app generates HydroIDs for users to connect them to the forthcoming ecosystem of Hydro smart contracts. This bounty is intended to foster broader adoption of Client Raindrop and the Hydro mobile app by offering website administrators tools to easily integrate Hydro MFA into their sites. Specifically, this task is to create a OctoberCMS plug-in in the plugin repository that integrates with the Hydro API to offer a seamless implementation of the MFA workflow. The goal is to allow sites built on the OctoberCMS platform to seamlessly integrate an out-of-the-box Hydro 2FA workflow that can be easily customized to their sites.

**What are the deliverables?**

A OctoberCMS plug-in implementing the Client Raindrop process. For detailed information on this process, see the Hydro API documentation. [Our implementation guide](https://www.hydrogenplatform.com/docs/hydro/v1/) may be helpful as background information. Calls to the Hydro API should be made through an official Hydro SDK.

Our intent is for this module to be oriented toward login-style authentication. This is up for debate however, and we are more than happy to discuss the options. Regardless, a thorough justification for the ultimate implementation will be expected.

This module should have sufficient flexibility to be added as an authorization layer after one or more successful authorizations.

Developers may complete this module per their preference, but a suggested approach is to reference the [Hydro wordpress plug-in](https://wordpress.org/plugins/wp-hydro-raindrop/). A working and well-documented example with best-practice code should be provided. The completed result should enable OctoberCMS websites and custom implementations of OctoberCMS websites to easily integrate Hydro 2FA into their sites.

The list of deliverables can be found over at [Hydro WP Raindrop MFA Plugin v2.0 Architecture / Features Guidelines](https://docs.google.com/document/d/1OEYajbkXZUZ2gviP3gJvO9rdW5yUgSOWTclbdeKCCts/edit?usp=sharing).

The first phase involves delivering features Point 1, Point 2 and Point 3 of the above architecture guideline.

The deliverables also include researching other popular plugins which provide similar capabilities for their users and coming up with a strategy to outdo them. You will be required to present and brainstorm on each deliverables on the discord channel with the Hydro core team and DA so as to create a plugin that can truly surpass others by a long way.

**Timeframe?**

We propose 4 weeks as the timeframe for completion of this task.

**Submission process?**

This task is reserved for a developer who wishes to remain anonymous.

**Oversight Process**

([@HarshRajat](https://github.com/HarshRajat)) will oversee the completion of this task.

**Reward Structure**

Once you have been selected, you will have 4 weeks to complete the task. The time frame begins as soon as we award the task to the candidate by communication within this thread.

During this time we will be able to provide some support around questions about the workflow on [Discord](https://discordapp.com/channels/416248342381854721/416269213557194764). 

During this time the candidate needs to update the codebase regularly in a subrepo of our official github: [https://github.com/HydroBlockchain](https://github.com/HydroBlockchain).  This will be setup and conveyed to the candidate by the assigned DA.

If the task is not completed within the timeframe we reserve the right to offer an extension, or transfer the task to another candidate. If no extension is granted, then we reserve the right to continue on the codebase committed. The fractional disbursement for it, if any, would be given at our discretion. 

Once the task is completed we will test the plug-in for efficiency and whether or not it correctly incorporates the Hydro workflow. If we approve the plug-in, we will then send you 800,000 Hydro.

**Comment by HarshRajat** [comment]
@crypt0h3nk please confirm your ether address: 0x9DBbAD2B3E15552735039B05C3e247A5fC1E6EF5

**Comment by crypt0h3nk** [comment]
Confirmed.
