### ISSUE TITLE
HYDRO RAINDROP, THE FUTURE OF 2FA AND ONLINE SECURITY

### ISSUE THREAD

**Issue by Dannyrita** [HydroBlockchain/hcdp#25]
Content: 
https://steemit.com/hydrogen/@ritabella/hydro-raindrop-the-future-of-2fa-and-online-security

Etherium wallet: 0xf2e9A679ed14dbA7B64B15a4bF3afB544714A0d7

**Comment by Dannyrita** [comment]
https://steemit.com/hydrogen/@ritabella/hydro-raindrop-the-future-of-2fa-and-online-security

Etherium wallet: 0xf2e9A679ed14dbA7B64B15a4bF3afB544714A0d7

Thanks dev

**Comment by paradise6334** [comment]
https://steemit.com/hydrogen/@ritabella/hydro-raindrop-the-future-of-2fa-and-online-security

0xd2446FbC32f6972d7672D9AF6d30425096F50AD8
