### ISSUE TITLE
3,000,000 HYDRO to create a Gift Card Ethereum Smart Contract

### ISSUE THREAD

**Issue by milvinae** [HydroBlockchain/hcdp#253]
## Project Details ##
3,000,000 HYDRO to create an Ethereum smart contract on top of [Hydro Snowflake](https://medium.com/hydrogen-api/examining-erc-1484-hydro-snowflake-cc3753a5ff52) that allows a business to create gift cards for their services and for a user to redeem these gift cards, with unique characteristics.

### Background: ###
* The gift card market is one of the fastest growing parts of commerce, and is expected to reach over $1 Trillion in value globally
* Building gift card infrastructure will allow users to “pay” for things in the Hydrogen ecosystem from pre-loaded and defined amounts tied to their Snowflake

### Features: ###
* **Issuer creates the gift card** - total number to be issued, unique codes on the cards, ID of Snowflake for business entity, amounts available for each card, date of expiry
* **Buy the gift card** - exchange an exact amount of Hydro for a pre-defined value on the gift card
* **Segregation** - Put an electronic record of the gift card amount in a segregated part of the Hydro user’s Snowflake (almost like an escrow contract), they can’t use it anywhere else, it can’t be exchanged for fiat or other crypto
* **Drawdown** - Only allow the user to draw down the exact amount of the gift card. At 0 HYDRO the gift card is burned.
* **Redeem** - allow a user to authenticate the gift card ID and redeem at selected merchant that is tied to the SNowflake ID only
* **Authenticate** - redemption of a gift card via Hydro Raindrop only
* **Balance** - Retrieve a balance on a gift card via a function
* **Accepting a Gift Card** - Create a function that any business can add to a dApp to accept a gift card ID

### Other Notes: ###
* Gift cards have some of the highest fraud rates in e-commerce, 10% of all fraud attempts in e-commerce are on downloadable gift cards
* Many people will want to have the ability to swap or transfer gift cards, this is a growing marketplace

### What is the development you want done? ###
Solidity code, in the form of an open-source smart contract, deployed to the Hydro Blockchain GitHub repository for public use.

## What are the deliverables? ##
Solidity code, in the form of an open-source smart contract, deployed to the Hydro Blockchain GitHub repository for public use.

## Timeframe? ##
We propose one month as the timeframe for completion of this task.

## Submission process? ##
First, **_comment on this issue to declare your willingness to complete the task_**. Next, fill out the [Gift Cards Smart Contract Claim Form](https://docs.google.com/forms/d/1KI7l7FTZX1pf9_QLJ11vFN59-4A_CB6XHSE8K8N2sdM). We will evaluate candidates factoring in their qualifications, Github activity, and the order in which they expressed interest.

## Oversight Process ##
One of the DAs will be assigned to oversee the completion of this task once it’s awarded.

## Reward Structure ##
Once you have been selected, you will have **one month** to complete the task. The time frame begins as soon as we award the task to the candidate by communication within this thread.
During this time we will be able to provide some support around questions about the workflow on Discord.

During this time the candidate needs to update the codebase regularly in a subrepo of our [official Github](https://github.com/HydroBlockchain).  This will be setup and conveyed to the candidate by the assigned DA.

If the task is not completed within the timeframe we reserve the right to offer an extension, or transfer the task to another candidate. If no extension is granted, then we reserve the right to continue on the codebase committed. The fractional disbursement for it, if any, would be given at our discretion.

Once the task is completed we will test the plug-in for efficiency and whether or not it correctly incorporates the Hydro workflow. If we approve the plug-in, we will then send you 3,000,000 Hydro.

**Comment by kdmukai** [comment]
Yes! Super interested in building this! FYI the link to the claim form is broken.

**Comment by mitdralla** [comment]
> Yes! Super interested in building this! FYI the link to the claim form is broken.

Hello @kdmukai that is great! The form link is now fixed - please fill it out at your earliest convenience.

**Comment by clemlak** [comment]
I'm interested! :)

**Comment by Luiserebii** [comment]
I'm interested!

**Comment by mitdralla** [comment]
This task is assigned to @kdmukai  - we will reach out with next steps. 👍

**Comment by mitdralla** [comment]
Completed. Thank you!
