### ISSUE TITLE
3,000,000 HYDRO to create an Invoicing Ethereum Smart Contract

### ISSUE THREAD

**Issue by milvinae** [HydroBlockchain/hcdp#254]
## Project Details ##
3,000,000 HYDRO to create an Ethereum smart contract on top of [Hydro Snowflake](https://medium.com/hydrogen-api/examining-erc-1484-hydro-snowflake-cc3753a5ff52) that allows a business to invoice another business or consumer for a specific amount, on a specified date, and in a certain amount of Hydro.

### Background: ###
* The e-invoice market is expected to grow to over $20 Billion in five years.
* By validating, authenticating, and cutting down on transaction fees, blockchain technology can disrupt the invoicing market.

### Features: ###
* **Tying to Snowflake** - a Snowflake ID is able to create one or more digital invoices for one or more Snowflake IDs
* **Create** - Create an invoice, open fields for amount, invoice number, invoice date, invoice terms (net 30, net 60, etc), and payment terms
* **Edit** - Edit an existing invoice ID.
* **Cancel** - Cancel an existing Invoice ID
* **Accounts Receivable** - Add an open invoice amount to an accounts receivable number tied to the Snowflake ID of the receiving party
* **Accounts Payable** - Add an open invoice amount to an accounts payable number tied to the Snowflake ID of the paying party.
* **Send** - Distribute an invoice number to another Snowlake ID (e.g. and accountant) who has read only access to the invoice
* **Confirm Payment** - use the Hydro Raindrop smart contract to confirm receipt and payment of the invoice
* **Dispute** - create a flag for a disputed invoice payment, amount, date, etc

For comparative functionality, please see [Paypal](https://developer.paypal.com/docs/api/invoicing/v1/) developer documentation.

## What is the development you want done? ##
Solidity code, in the form of an open-source smart contract, deployed to the Hydro Blockchain GitHub repository for public use.

## What are the deliverables? ##
Solidity code, in the form of an open-source smart contract, deployed to the Hydro Blockchain GitHub repository for public use.

## Timeframe? ##
We propose one month as the timeframe for completion of this task.

## Submission process? ##
First, **_comment on this issue to declare your willingness to complete the task_**. Next, fill out the [Gift Cards Smart Contract Claim Form](https://docs.google.com/forms/d/15Yn2DAqNxwr8N7kfcTV2HX3WAAJcDiML4D47qhUMV2c). We will evaluate candidates factoring in their qualifications, Github activity, and the order in which they expressed interest.

## Oversight Process ##
One of the DAs will be assigned to oversee the completion of this task once it’s awarded.

## Reward Structure ##
Once you have been selected, you will have **one month** to complete the task. The time frame begins as soon as we award the task to the candidate by communication within this thread.
During this time we will be able to provide some support around questions about the workflow on Discord.

During this time the candidate needs to update the codebase regularly in a subrepo of our [official Github](https://github.com/HydroBlockchain).  This will be setup and conveyed to the candidate by the assigned DA.

If the task is not completed within the timeframe we reserve the right to offer an extension, or transfer the task to another candidate. If no extension is granted, then we reserve the right to continue on the codebase committed. The fractional disbursement for it, if any, would be given at our discretion.

Once the task is completed we will test the plug-in for efficiency and whether or not it correctly incorporates the Hydro workflow. If we approve the plug-in, we will then send you 3,000,000 Hydro.

**Comment by clemlak** [comment]
Let's do this!

**Comment by Luiserebii** [comment]
I'm interested in completing this task, and am eager to hear back!

**Comment by mitdralla** [comment]
This task is assigned to @clemlak - we will reach out with next steps. 👍
