### ISSUE TITLE
4,000,000 HYDRO to create a Product Orders Ethereum Smart Contract

### ISSUE THREAD

**Issue by mitdralla** [HydroBlockchain/hcdp#256]
## Project Details ##
4,000,000 HYDRO to create an Ethereum smart contract on top of Hydro Snowflake that allows a business to create SKUs and inventory management on goods to be sold to customers. 

### Background: ###
* Stock keeping units (SKUs) describe specific product variations, taking into account any combination of: attributes, currency, and cost. For example, a product may be a t-shirt, whereas a specific SKU represents the size and color version of that shirt. 
* By assigning unique SKUs and tracking their ownership within Snowflake IDs, customers can be sure they are making a legitimate purchase, and vendors can validate shipment and returns.

### Features: ###
* **Create a SKU** - assign a unique ID to a product
* **Define attributes** - define the attributes of the product to store on-chain, such as gender, size, color, materials
* **Inventory** - add a SKU to a group of other SKUs to form the foundation of inventory management
* **Shipping** - define shipping parameters of the SKU or inventory
* **Price** - define price of the SKU or inventory, accept gift cards and coupons from other Hydro Snowflake smart contracts
* **Create Order** - create an order, tied to a Snowflake ID of a business and an end-user containing date, SKU info, shipping info
* **Create Barcode** - create a unique barcode tied to an order
* **Authenticate Purchase** - use Hydro Raindrop to confirm a purchase
* **Authenticate Shipment** - perform an authentication of the SKU(s) being sent and reduce from inventory
* **Authenticate Receipt** - perform an authentication of the product SKU being received by scanning the barcode and storing in the Snowflake
* **Dispute** - create a flag on a Snowflake for a disputed order or shipment

For comparative functionality, please see [Stripe developer documentation](https://stripe.com/docs/api/skus). 

## What is the development you want done? ##
Solidity code, in the form of an open-source smart contract, deployed to the Hydro Blockchain GitHub repository for public use.

## What are the deliverables? ##
Solidity code, in the form of an open-source smart contract, deployed to the Hydro Blockchain GitHub repository for public use.

## Timeframe? ##
We propose one month as the timeframe for completion of this task.

## Submission process? ##
First, **_comment on this issue to declare your willingness to complete the task_**. Next, fill out the [Gift Cards Smart Contract Claim Form](https://docs.google.com/forms/d/1jv3OohohYDlc9bmydD8FfdfPSinrabcs_NqrWmMq6uA). We will evaluate candidates factoring in their qualifications, Github activity, and the order in which they expressed interest.

## Oversight Process ##
One of the DAs will be assigned to oversee the completion of this task once it’s awarded.

## Reward Structure ##
Once you have been selected, you will have **one month** to complete the task. The time frame begins as soon as we award the task to the candidate by communication within this thread.
During this time we will be able to provide some support around questions about the workflow on Discord.

During this time the candidate needs to update the codebase regularly in a subrepo of our [official Github](https://github.com/HydroBlockchain).  This will be setup and conveyed to the candidate by the assigned DA.

If the task is not completed within the timeframe we reserve the right to offer an extension, or transfer the task to another candidate. If no extension is granted, then we reserve the right to continue on the codebase committed. The fractional disbursement for it, if any, would be given at our discretion.

Once the task is completed we will test the plug-in for efficiency and whether or not it correctly incorporates the Hydro workflow. If we approve the plug-in, we will then send you 4,000,000 Hydro.

**Comment by amiromayer** [comment]
Interested 🙂

**Comment by Luiserebii** [comment]
I'm more than interested!

**Comment by emekauser** [comment]
I am interested in working on this

**Comment by merlox** [comment]
Hey I'm interested in working on this, is this task still open @mitdralla? When it comes to barcodes, it will have to be generated using an external API, is that allowed?

**Comment by mitdralla** [comment]
hey @merlox that should not be an issue, we will just want to make sure we have the right license to use things, can it scale etc.

**Comment by mitdralla** [comment]
This task is assigned to @merlox and can begin immediately.

**Comment by merlox** [comment]
Alright I'll get to it.

**Comment by mitdralla** [comment]
Fantastic!
