### ISSUE TITLE
3,000,000 HYDRO to Create a Smart Contract that Ties Off-Chain Financial Account Data to Hydro Snowflake

### ISSUE THREAD

**Issue by mitdralla** [HydroBlockchain/hcdp#257]
## Project Details ##
3,000,000 HYDRO to create an Ethereum smart contract that ties Off-Chain financial account data to [Hydro Snowflake ERC-1484](https://medium.com/hydrogen-api/examining-erc-1484-hydro-snowflake-cc3753a5ff52). This utility smart contract can be referenced by other dApp developers and designers in future builds, for example, to build banking, bill paying, credit, investing, and payment products.

### Problem Statement: ###
Linking financial accounts, such as bank account numbers, credit card numbers, and other products can be tedious and time consuming when using applications. Applications like Plaid have built multi-billion dollar valuations to solve this problem completely off-chain, but there are massive security flaws with their centralized database and storage of user credentials and account data. ERC-1484 and modern encryption can make this process more secure, and power dozens of future applications. 

### Features Proposed: ###
* **Link credit card** - link credit card number, expiry, address, name, CVV number
* **Link bank account** - link bank account number, user ID, password to a unique Snowflake ID
* **Link investment account** - link investment account number, user ID, password to a unique Snowflake ID
* **Encrypt** - obfuscate the data on-chain
* **Refresh** - re-authenticate the user data and delete the old record
* **De-link** - remove a financial account from a Snowflake ID

For reference documentation, please see the [Plaid](https://plaid.com/docs/) or [Quovo](https://api-docs.quovo.com/) API documentation.

## What is the development you want done? ##
Solidity code, in the form of an open-source smart contract, deployed to the Hydro Blockchain GitHub repository for public use.

## What are the deliverables? ##
Solidity code, in the form of an open-source smart contract, deployed to the Hydro Blockchain GitHub repository for public use.

## Timeframe? ##
We propose 2-3 weeks as the timeframe for completion of this task.

## Submission process? ##
First, **_comment on this issue to declare your willingness to complete the task_**. Next, fill out the [Off-Chain Smart Contract Claim Form](https://docs.google.com/forms/d/1tSWFYDrDNOnsMoMEUFdhpwGnDiwxRYkuwW5hPtIPgoI). We will evaluate candidates factoring in their qualifications, Github activity, and the order in which they expressed interest.

## Oversight Process ##
One of the DAs will be assigned to oversee the completion of this task once it’s awarded.

## Reward Structure ##
Once you have been selected, you will have **2-3 weeks** to complete the task. The time frame begins as soon as we award the task to the candidate by communication within this thread.
During this time we will be able to provide some support around questions about the workflow on Discord.

During this time the candidate needs to update the codebase regularly in a subrepo of our [official Github](https://github.com/HydroBlockchain).  This will be setup and conveyed to the candidate by the assigned DA.

If the task is not completed within the timeframe we reserve the right to offer an extension, or transfer the task to another candidate. If no extension is granted, then we reserve the right to continue on the codebase committed. The fractional disbursement for it, if any, would be given at our discretion.

Once the task is completed we will test the plug-in for efficiency and whether or not it correctly incorporates the Hydro workflow. If we approve the plug-in, we will then send you 3,000,000 Hydro.

**Comment by Luiserebii** [comment]
I'm interested!

**Comment by kdmukai** [comment]
This one is pretty cool. Interested!

**Comment by clemlak** [comment]
I'm interested too!

**Comment by merlox** [comment]
I'm interested in working on this. I'll implement commitment schemes with signed off-chain messages so that we can safely encrypt users' data on the blockchain while being able to recover those credentials. I can get it done in 2 weeks.

**Comment by solihinbleking** [comment]
👩‍👩‍👦

**Comment by merlox** [comment]
Any updates on this project @mitdralla ? I'm willing to do it.

**Comment by mitdralla** [comment]
This task is assigned to @merlox and will be overseen by @mitdralla.

**Comment by merlox** [comment]
Awesome thanks.

**Comment by mitdralla** [comment]
Hello @merlox - Thank you for completing this HCDP task. https://github.com/merlox/hydro-finance Could you please provide your ETH address below?

**Comment by merlox** [comment]
Sure, my address is 0x732Dac7623a3BC6b771DD4C1B75E60A9a240D9c7

**Comment by mitdralla** [comment]
txn: https://etherscan.io/tx/0xfee2a17e2c67f9a32baa4bf4e86e690d4b0f8089a4114ce59d9d64723d26eec9
