### ISSUE TITLE
EDUCATIONAL CONTENT

### ISSUE THREAD

**Issue by Dannyrita** [HydroBlockchain/hcdp#26]
Link to my posted content: 

https://steemit.com/hydrogen/@ritabella/hydro-raindrop-the-future-of-2fa-and-online-security

Etherium wallet: 0xf2e9A679ed14dbA7B64B15a4bF3afB544714A0d7

**Comment by ghost** [comment]
We are no longer accepting content submissions as part of the HCDP. Thank you for your submission.
