### ISSUE TITLE
4,000,000 HYDRO to Create a Smart Contract to Power Charging Interest in Many Future Savings, Lending, Credit, and Mortgage Hydro dApps

### ISSUE THREAD

**Issue by mitdralla** [HydroBlockchain/hcdp#264]
## Project Details ##
4,000,000 HYDRO to create an Ethereum smart contract on top of [Hydro Snowflake](https://medium.com/hydrogen-api/examining-erc-1484-hydro-snowflake-cc3753a5ff52) that allows a certain percentage of interest on a defined principal amount, in HYDRO, to accrue and be charged (or paid) to a wallet tied to a SnowflakeID, and then for that balance to automatically be withdrawn (or paid). The smart contract will guarantee that the money is in the account by enforcing an escrow of the accruing payment within the wallet, thus eliminating payment default, or fraud from institutions. This utility smart contract will power charging interest in many future savings, lending, credit, and mortgage Hydro dApps. There will be Layer-3 dApps and Layer-4 APIs that hook into this utility smart contract function.

### Background: ###
* The market for interest bearing notes and accounts is huge globally
* The market for interest paying debt products is even larger globally
* One of the largest problems facing the lending markets is default; in the student loan market alone, 22% of all borrowers default on their payments every year
* From 2009-2017, nearly 500 banks failed in the U.S. costing the FDIC over $75 Billion to make clients whole
* By holding interest from an issuer or borrower in an escrow within a Snowflake, counterparties can eliminate fraud, default, and validate all terms on-chain

### Features: ###
* **Create Interest Rate** - et a defined interest rate from 0%-100%
* **Set Principal Amount** - set the principal amount that the interest will be calculated on
* **Define Snowflake IDs** - set the Snowflake ID for the payer and the payee
* **Accrual** - set the accrual date for the interest payments (the default can be daily)
* **Payment Schedule** - set the payment schedule for the interest payments (the default can be monthly)
* **End Date** - set the end date, or term, of the payments. For savings the default can be infinite, for loans and credit, the default can be 1 year. 
* **Escrow** - remove the set amount of HYDRO from the SnowflakeID wallet to an escrow contract on the payment schedule intervals, to insure there will be no default
* **Send Interest** - distribute the interest HYDRO from the escrow on the Payment Schedule date
* **Send Principal** - in the case of a debt contract, send the principal amount on the contract from the Snowflake ID on the End Date.
* **Confirm Payment** - use the Hydro Raindrop smart contract to confirm receipt and payment of the interest from the payer to the payee
* **Dispute** - create a flag for a disputed interest payment

The interest rate, once set, cannot be edited or modified. The terms can be deleted by mutual consent of both parties via a Hydro Raindrop transaction.

## What is the development you want done? ##
Solidity code, in the form of an open-source smart contract, deployed to the Hydro Blockchain GitHub repository for public use.

## What are the deliverables? ##
Solidity code, in the form of an open-source smart contract, deployed to the Hydro Blockchain GitHub repository for public use.

## Timeframe? ##
We propose 2-3 weeks as the timeframe for completion of this task.

## Submission process? ##
First, **_comment on this issue to declare your willingness to complete the task_**. Next, fill out the [Off-Chain Smart Contract Claim Form](https://docs.google.com/forms/d/1MN08fC6JA4mwQ7a67DgykraIl5R8IJ0oO7RHt8Tt-20). We will evaluate candidates factoring in their qualifications, Github activity, and the order in which they expressed interest.

## Oversight Process ##
One of the DAs will be assigned to oversee the completion of this task once it’s awarded.

## Reward Structure ##
Once you have been selected, you will have **2-3 weeks** to complete the task. The time frame begins as soon as we award the task to the candidate by communication within this thread.
During this time we will be able to provide some support around questions about the workflow on Discord.

During this time the candidate needs to update the codebase regularly in a subrepo of our [official Github](https://github.com/HydroBlockchain).  This will be setup and conveyed to the candidate by the assigned DA.

If the task is not completed within the timeframe we reserve the right to offer an extension, or transfer the task to another candidate. If no extension is granted, then we reserve the right to continue on the codebase committed. The fractional disbursement for it, if any, would be given at our discretion.

Once the task is completed we will test the plug-in for efficiency and whether or not it correctly incorporates the Hydro workflow. If we approve the plug-in, we will then send you 4,000,000 Hydro.

**Comment by ricktobacco** [comment]
Hello I am interested in taking this on

**Comment by chainpioneer** [comment]
Interested in participating

**Comment by Luiserebii** [comment]
I'm interested!

**Comment by mitdralla** [comment]
This task is assigned to @ricktobacco - we will reach out with next steps. 👍

**Comment by ricktobacco** [comment]
Repo for the project: https://github.com/ricktobacco/hydro-glacier
Notes: accrual schedule is effectively compound interest main; challenges are with determining how much interest must be locked in escrow upfront by payer before payee's principal is release:
-->with no end date (indefinite period for savings) there must be an explicit number of payments indicated. 
-->with payment scheduling, the process of retrieving interest from escrow by the payee is triggered manually...the math library from Bancor is used to calculate how much interest will be owed upfront. if the borrower repays the principal ahead of end date, remaining interest payments are refunded.

**Comment by ricktobacco** [comment]
Contract is ready for review!
