### ISSUE TITLE
*PLEASE MAKE NOTE THAT THIS IS A FORM FOR CREATING A BOUNTY NOT SUBMITTING A BOUNTY**  **What is the development you want done?**  **What are the deliverables?**  **Timeframe?**  **Submission process?**

### ISSUE THREAD

**Issue by velat3434** [HydroBlockchain/hcdp#266]
**PLEASE MAKE NOTE THAT THIS IS A FORM FOR CREATING A BOUNTY NOT SUBMITTING A BOUNTY**

**What is the development you want done?**

**What are the deliverables?**

**Timeframe?**

**Submission process?**

**Comment by HarshRajat** [comment]
Hi @velat3434,

You might have been trying to create a proposal for an HCDP Task for us to review. Closing this since it seems like an error. Please resubmit the task following the proper rules and we DAs will review it as soon as we can.
