### ISSUE TITLE
Update on Reddit Bounty?

### ISSUE THREAD

**Issue by RoastedPecans** [HydroBlockchain/hcdp#273]
**What is your suggestion?**
I saw this post on Reddit earlier today (https://www.reddit.com/r/ProjectHydro/comments/7tutvh/announcing_the_project_hydro_bounty_program_with/) and was wondering if there were any updates on the Reddit bounty program?  The link in the article linked is dead so couldn't check it out on there and I didn't see updates on either Reddit or on this Github. If it has not been claimed yet I might be interested in developing it in the coming weeks.

Thanks!

**Comment by milvinae** [comment]
Sorry this ended over a year ago. The only tasks are the ones posted here
