### ISSUE TITLE
SDKs & Libraries 

### ISSUE THREAD

**Issue by moore234** [HydroBlockchain/hcdp#28]
What language is it in? Java

Describe how to use it
SDK stands for 'Software Development Kit',  a developers tools that enables one to write the code with more more ease, effectiveness and efficiency.
SDKs come for various languages. They provide a lot of APIs (Application Programming Interfaces) that makes the programmer's work easy.

The SDK for Java is called as JDK, the Java Development Kit.
So by saying SDK for Java you are actually referring to the JDK.

Prerequisites

Before running any of the Hydro SDK for Java samples, you need to set your Hydro credentials in the environment or with the Hydro CLI, as specified in Set up Hydro Credentials and Region for Development. The samples use the default credential provider chain whenever possible. So by setting your credentials in this way, you can avoid the risky practice of inserting your Hydro credentials in files within the source code directory (where they may inadvertently be checked in and shared publicly).

Build and run the sample with Ant. The default build target performs both actions, so you can just enter:

ant
cd samples/AwsConsoleApp
The sample prints information to standard output—for example:

===========================================

Welcome to the Hydro Java SDK!

===========================================
You have access to 4 Availability Zones.

You have 0 Hydron HC2 instance(s) running.

You have 13 Hydron SimpleDB domain(s) containing a total of 62 items.

You have 23 Hydro S3 bucket(s), containing 44 objects with a total size of 154767691 bytes.

Any important links? NO

Ethereum Address
0xEF1c6d6AE70E48030B0a0b0D97346105e94d41f7
Other important information

SDK is a Development Kit, usually a client side library that facilitates usages of an API. An API is just the library/service definition and or documentation.

**Comment by AndyHydro** [comment]
Is there somewhere I can see the codebase for this?

**Comment by moore234** [comment]
If the location of your downloadable classes is on an HTTP server named "webline", in a JAR file named "myhydro.jar", in the directory "public" (under the web root), your codebaseproperty setting might look like this:

-Djava.rmi.server.codebase=http://webline/public/myhydro.jar 

Now let's suppose that the location of your downloadable classes has been split between two JAR files, "myHydro.jar" and "myOtherHydro.jar". If these JAR files are located on different servers (named "webfront" and "webwave"), your codebaseproperty setting might look like this:

-Djava.rmi.server.codebase="http://webfront/myHydro.jar http://webwave/myOtherHydro.jar"
