### ISSUE TITLE
Article on Machine Learning and How we can use Hydrogen's ION API

### ISSUE THREAD

**Issue by rjohal02** [HydroBlockchain/hcdp#29]
**https://medium.com/@ranjotj/machine-learning-how-to-effectively-use-your-data-34ffd7aa793a**

**0xbe2cdecac7797fb2984e1b0bf491144fc2a3cfab**

**Comment by rjohal02** [comment]
Have also posted the same on Steemit and tweeted about the same on twitter handle

https://steemit.com/machinelearning/@rjohal/machine-learning-how-to-analyze-your-data

**Comment by ghost** [comment]
This is an interesting article, but outside of the scope of the HCDP.
