### ISSUE TITLE
Educational content

### ISSUE THREAD

**Issue by diamondbea** [HydroBlockchain/hcdp#39]
**Link to the posted content**
https://steemit.com/ico/@sweedy/micro-deposit-verification-process-in-hydrogen-platform
**Ethereum Address**
0xD520D01a6D2820464D8B2a19F54011b05237D44A

**Comment by ghost** [comment]
Thanks for the article @diamondbea! An interesting read, but unfortunately it doesn't quite meet HCDP standards. We appreciate the effort, though, and thank you for being part of the ecosystem.
