### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by niawjunior** [HydroBlockchain/hcdp#41]
https://drive.google.com/open?id=1R0VDRDwP89IsLTtqhd6o-gR0SGqD5tTL

![alt text](https://image.ibb.co/gJwHkd/1.png)
![alt text](https://image.ibb.co/nmnZWJ/2.png)
![alt text](https://image.ibb.co/kJuRdy/3.png)

0xcF4CA355eC55724DEC46404B360bC00E516f6E8F

**Comment by ghost** [comment]
These look good! Unfortunately this isn't quite in scope for the HCDP
