### ISSUE TITLE
Hydro 

### ISSUE THREAD

**Issue by humblemee** [HydroBlockchain/hcdp#52]
https://medium.com/@713d5939e54a/c2935c45eddd

0xB6a101a1A827141deb9090C2fAE24d62a8aCc6c1

**Comment by ryamnery** [comment]
Educational Content

**Comment by Noblegirl** [comment]
Nice one

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
