### ISSUE TITLE
HYDRO: A TOOL FOR A BETTER FUTURE SECURITY TO ONLINE DATA/INFORMATION

### ISSUE THREAD

**Issue by Nnemummy** [HydroBlockchain/hcdp#53]
https://steemit.com/hydrogen/@adaora26/hydro-a-tool-for-a-better-future-security-to-online-datas-information

0x88F86821e3F1e9eE25599757cC7063B8564C3201

**Comment by stirf** [comment]
nice

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
