### ISSUE TITLE
UNDERSTANDING THE DYNAMICS, AND THE FOCUS OF HYDROGEN PROJECT 

### ISSUE THREAD

**Issue by Osakuni** [HydroBlockchain/hcdp#59]
https://medium.com/@okparablessing356/understanding-the-dynamics-of-the-hydrogen-project-bef2790cd800

0x581E8391D2cBFCed1117225DdEc6cA3DD839618f

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
