### ISSUE TITLE
Fund integration and distribution for charity group

### ISSUE THREAD

**Issue by ohmghimire** [HydroBlockchain/hcdp#6]
Language is english English
To  integrate fund for easy fund collection by mobile payment system

0xE274A6953cD311c1E7931B82C64614a6f89f1122
Its a starting volunteering and charity non for profit organisation for Australia which will run with low budget targeting to offer help to homless and sick kids.

**Comment by AndyHydro** [comment]
This does not fit any of our current open submissions
