### ISSUE TITLE
EDUCATIONAL CONTENT- USES OF HYDRO RAINDROP AND IT’S OPENING TO THE PUBLIC

### ISSUE THREAD

**Issue by lynkels** [HydroBlockchain/hcdp#62]
https://steemit.com/hydro/@lynkels/uses-of-hydro-raindrop-and-it-s-open-doors-to-the-public

0x245586Fe421dA7766772cbfe2acE0e150de844a6

**Comment by AnuragHydro** [comment]
Thanks for your submission - currently, there is already a lot of content that summarizes our white paper, so for HCDP submissions, we are looking for content that adds a layer of knowledge or unique potential applications beyond the content that is currently out there.
