### ISSUE TITLE
Hydro

### ISSUE THREAD

**Issue by Noblegirl** [HydroBlockchain/hcdp#63]
https://medium.com/@7cf520cc30f6/c1fcb0420e5a

0xb016845bC656d639b2C1ca64B08b018C99f2630C

**Comment by AnuragHydro** [comment]
Thank you for the submission! We already have a lot of content that provides simplified explanations of our white paper and existing product offerings - educational content moving forward will require explanations of new and unique ways to apply the content that is already available.
