### ISSUE TITLE
Educational Contents

### ISSUE THREAD

**Issue by Romanbank** [HydroBlockchain/hcdp#64]
Here is the my video link about the project

https://youtu.be/-V9oQthIRIo

Wallet ID: 
0xc6888cDbFBfA620B4e078933415BDc5D59d2C9Cf

**Comment by cosare** [comment]
Wow its a good project,,keep up the good work

**Comment by AnuragHydro** [comment]
Hi Romanbank, thank you for your submission! I love the passion - currently, we're looking for content that adds a new or innovative spin on some of the implications of Hydro or explains in detail how the app functions rather than simply explaining the general value of multi-factor authentication.
