### ISSUE TITLE
WHY HYDROGEN CAN BE GREAT IN FUTURE

### ISSUE THREAD

**Issue by Rahilababe07** [HydroBlockchain/hcdp#65]
https://medium.com/@6872fe82c21/67ad21586892

0x816DD5d18d558115d0Ce96f9187AD7A6F0c55474

**Comment by stirf** [comment]
admin so  active thats why project is successfull more power hydro...

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
