### ISSUE TITLE
Project hydro!!! 

### ISSUE THREAD

**Issue by Timmy9419** [HydroBlockchain/hcdp#66]
**Link to the posted content**
https://medium.com/@22292d71dfe6/d96df0c8fa73

**Ethereum Address**
0xB5d8211cD393E6aca01506cf41f7E1123B0aF76C

**Comment by stirf** [comment]
nice hope im recieve now hydro

**Comment by stirf** [comment]
nice hope im recieve now hydro

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
