### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by Ritarahayu** [HydroBlockchain/hcdp#67]
https://medium.com/@ritarahayutila/first-look-hydro-snowflake-6254b357a16f

0x52D3b4674F44F5110D7F9df34e298Ae6b7d98eA6

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide enough detailed information.
