### ISSUE TITLE
HYDRO THE DIFFERENT CRYPTO

### ISSUE THREAD

**Issue by sandip33** [HydroBlockchain/hcdp#69]
I believe that this project is one of the best project and much bigger and important than the other crypto project.
The hydrogen team is really skilled,hardworking and skillfull.
The apps that is to be released are really important and useful. 
With bigger exchanges and marketing this project has the capacity to go beyond all boundaries. 
I from my heart wish hydrogen project to be successful and the team should be rewarded for there hardwork. 
 
Buy and hold hydro when it is really cheap ..believe me you will earn real profit

**Comment by AnuragHydro** [comment]
Thanks for your submission - approved educational content requires the creation of open, public content that adds understanding beyond what is readily available for someone learning more about Hydro
