### ISSUE TITLE
Educational Content 

### ISSUE THREAD

**Issue by Samuel-Chuku** [HydroBlockchain/hcdp#7]
https://steemit.com/hydogen/@sammy-gates/maximum-security-guaranteed-by-hydrogen

Ethereum  address: 0x1A334a6974070c52AB42701c113929B294f5D67B
Telegram  username: @gates01

**Comment by AndyHydro** [comment]
Please include your ethereum address so we can send you the tokens if you are approved

**Comment by timingtrader** [comment]
Hi,
How much sir??
Thanks in advance,
Gianluca Boccia

Il Mer 16 Mag 2018, 17:23 AndyHydro <notifications@github.com> ha scritto:

**Comment by cuong777** [comment]
Youtube Content link: https://www.youtube.com/watch?v=bCX8CXMkLeQ
My Telegram username: @cuong7
ETH Wallet: 0x3784f0ED554C5cf26F4444B52f3CE7EfD3b7c6C1

**Comment by Samuel-Chuku** [comment]
Done @AndyHydro

**Comment by ghost** [comment]
We are no longer accepting content submissions as part of the HCDP. Thank you for your submission.
