### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by niawjunior** [HydroBlockchain/hcdp#70]
https://bit.ly/2rPYiVW

0xcF4CA355eC55724DEC46404B360bC00E516f6E8F

**Comment by niawjunior** [comment]
hi bro when i recieve this email  what should i do?

2018-05-24 0:40 GMT+07:00 Noah Zinsmeister <notifications@github.com>:

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.

**Comment by niawjunior** [comment]
Sorry, I just noticed that what I typed was not recorded in the article. TT
