### ISSUE TITLE
Educational Content:-Benefits of Hydro and its new Raindrop Technology 

### ISSUE THREAD

**Issue by jayhkz** [HydroBlockchain/hcdp#71]
https://steemit.com/hydrogen/@jayhk/benefits-of-hydrogen-token-and-its-new-raindrop-technology

0xf52B2b2606f5A8f043F51F796C9Be1fd76aF980A

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide a detailed, informative view of Hydrogen products.
