### ISSUE TITLE
Hydro Blocktank event in Tweet

### ISSUE THREAD

**Issue by ebunayo** [HydroBlockchain/hcdp#73]
https://medium.com/@ebunayo08/hydro-blocktank-event-in-tweet-cebe0c5e7afd

0x067ca205aaF09A8B724Cadd2f70A38f9AF2d150A

**Comment by AnuragHydro** [comment]
Thanks for the submission! This was innovative and helps people understand Hydro's role in helping build out a decentralized future in which people can interact with dApps seamlessly!

**Comment by ebunayo** [comment]
Great I was able to help in my bit to move the project forward. Will be around to add my best to the project
