### ISSUE TITLE
Educational Content

### ISSUE THREAD

**Issue by TedLivist** [HydroBlockchain/hcdp#75]
I created a thread on reddit on the brief summary of what Hydro is all about.
Here is the link
https://www.reddit.com/r/token/comments/8je99h/app_developer_hydrogen_platform_is_for_you/?utm_source=reddit-android

Telegram username: @Krypted

Ether address:
0xaF9938f9BB42AE0a111253Fb7b93716843f03Cd7

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products.
