### ISSUE TITLE
EDUCATONAL CONTENT  

### ISSUE THREAD

**Issue by Ralphblossom** [HydroBlockchain/hcdp#76]
EDUCATION CONTENT THE SECRET YOU NEVER KNEW ABOUT HYDROGEN: The Technology  of the financial application In Blockchain.

Hydrogen as the name implies is the first element in the world with the atomic number of 1 and atomic weight of 1.008. This implies Hydrogen to be the first token with great features in the blockchain technology from which other technologies are built.

Hydrogen Is a token with Application Programming Interface ( API ) built for programmers with all financial engineering needed to build projects and tools to set your brand apart.
Hydrogen APIs combine all of the core infrastructure needed to build leading Fintech architecture with all financial engineering needed to build projects and tools to set your brand apart from other projects. It enables financial system to seamlessly leverage the public blockchain with cloud applications throughout the financial services ecosystem can now benefit from the power of smart contracts, creating more secure, transparent and low cost financial products globally.

Hydrogen is different because it allows developers to seamlessly deploy blockchain in their existing application without the need to create expensive infrastructure.

ABOUT THE API ( Application Programming Interface)

The API provides core digital infrastructure to anchor your Fintech application with modules built for Fintech.
The API is divided into 3 parts, namely:

The Nucleus API

The Proton API

The Electron API.

THE NUCLEUS API
It's Importance and Uses includes :

Authentication
It has a single and multi factor API for authentication for security in blockchain development.

Client Onboarding
It helps to configure, store, encrypt client information and onboarding.

Accounts
It helps to Create and manage clients accounts and subaccounts.

Investment
It is an infrastructure to invest in. It has all the infrastructure you need to start a world leading digital investing solutions. This includes on boarding, risk profiting, KYC, portfolio, construction, trading, ongoing support and admin.
The platform built in this category include, asset allocation, hybrid advice, high-net worth management, thematic investing, mutual fund investing and offshore investing.

Savings :
The investment API helps clients make the right savings decision and provide them with industry leading tools, analysis and dashboard, which includes : micro-savings, pension savings, goal tracking and term deposits.

Insurance :
Hydrogen instantly digitize your current insurance experience. Instant digital account opening and document signing, blockchain documents, analytics and customer engagement tools are made available at your fingertips.

Wellness :
Hydrogen helps to simplify the financial platform by aggregating dozens of pieces of data to provide your clients with a dynamic snapshot of their finances, plus tools to help them achieve their goals.

PROTON API

It provides financial engineering to power your fintect application in the blockchain technology.

ELECTRON API

It provides functionality to manage and grow your Fintech application in the blockchain technology.

HYDRO AUTHENTICATION: THE RAINDROP. 

Hydro enables new and existing private systems to seamlessly integrate and leverage the immutable & transparent dynamics of a public blockchain to enhance application and document security, identity management, transactions, and
artificial intelligence.

This can only be made possible with the use of the Hydro public blockchain "Hydro Raindrop" to enhance security through public authentication .

“Raindrop” - a transaction performed through
a smart contract that validates private system access publicly, and can complement existing private authentication methods. The technology is intended to provide additional security for sensitive financial data that is increasingly at risk from hacking and breaches.

Each Raindrop, in its entirety, is a set of five transactional parameters:

Sender - The address that must initiate the transaction.

Receiver - The transaction's destination. This corresponds to calling a method in a Hydro smart contract.

ID - An identifier that is associated with the System.

Quantity - A precise number of HYDRO to send.

Challenge - A randomly generated alphanumeric string .

While this blockchain-based authentication service was architected to help secure the Hydrogen API ecosystem, it is widely applicable to different platforms and systems. Because we feel that others can potentially benefit from
this verification layer, hydro is opening it up for use.
Just as Hydrogen will integrate it as a precondition for access to its API ecosystem, so too can any system add it to existing procedures and protocols.
Any platform - be it an API, application, enterprise software, gaming platform, etc. - can leverage Hydro for authentication purposes. Formal documentation will be available on "GitHub" for those who wish to incorporate this blockchain
layer into an authentication framework or REST API.

Entities Required for authentication:

Accessor - The party attempting to access a system. In the case of Hydrogen, the accessor is a financial institution or app utilizing the Hydrogen APIs for its core digital infrastructure.

System - The system or gateway that is being accessed by the Accessor.
For Hydrogen, the system is the Hydrogen API itself.

Hydro - The module that is utilized by the System to communicate and
interface with the blockchain.

Blockchain - The distributed public ledger that processes HYDRO transactions and contains the Hydro smart contracts, through which information may be pushed, pulled, or otherwise operated upon.

Three Stages of Authentication process:

Initialization
Raindrop
Validation

-Initialization begins with a System (e.g. Hydrogen) registering to use Hydro and obtaining credentials, enabling the system to communicate with the blockchain via the Hydro module. The System onboards an Accessor (e.g. a
financial institution) who registers a public address, and then passes the registered address to Hydro. This address is immutably written onto the blockchain to a whitelist stored in a Hydro smart contract. The System receives a confirmation that the address was whitelisted, which can also be verified as a publicly viewable event. System registration need only occur once, while Accessor whitelisting need only occur once per Accessor.

-After Initialization is complete, the core of the Hydro authentication process can begin. The Accessor, who must execute a Raindrop transaction, jumpstarts this process by requesting Raindrop details from the System, and the System routes the request to Hydro. Hydro generates a new Raindrop, stores certain
details immutably on the blockchain, and returns the full details to the Accessor via the System. The Accessor, equipped with all required information,
conducts a transaction from the registered address to a method in the Hydro smart contract. If the address is not whitelisted, the action is rejected - otherwise, it is recorded in the smart contract. It is important to note that this transaction should occur outside of the System, directly from the Accessor to the Blockchain, as it must be signed with the Accessor's private key (which only the Accessor should be able to obtain).

-The final step of the process is Validation.
In this step, the Accessor officially requests access to the System via the System's established
mechanism. Prior to implementing any of its standard authentication protocols,
the System asks Hydro whether or not the Accessor has performed a valid Raindrop transaction. Hydro interfaces with the smart contract, checks for validity, and responds with a true/false designation. The System is able to
decide how it should proceed based on this designation - if it is false, the System can deny access, and if it is true, the System can grant access.

My wallet address 

0xE664FEEBB95E06d0795Eea97a112A9cd56500258

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products.
