### ISSUE TITLE
WHY YOU SHOULD BE GLUED TO PROJECT HYDRO-HYDRO RAINDROP (THE FUTURE OF 2FA)

### ISSUE THREAD

**Issue by yudee1** [HydroBlockchain/hcdp#77]
Link: https://www.reddit.com/r/ProjectHydro/comments/8jtkgn/why_you_should_be_glued_to_project_hydro_hydro/

Ethereum Address: 0x8fB63d96D2eB10Be06B7CE97F09f1C10b871b334

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
