### ISSUE TITLE
EDUCATIONAL CONTENT - Hydrogen, first look at the Hydro token and the benefits of the Raindrop system.

### ISSUE THREAD

**Issue by connor187** [HydroBlockchain/hcdp#78]
https://steemit.com/cryptocurrency/@veigar/hydrogen-first-look-at-the-hydro-token-and-the-benefits-of-the-raindrop-system

Eth address: 0xAb7e0c5e97940C046eE969691d52c6deF4886A6a

Steemit account: @Veigar

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
