### ISSUE TITLE
HYDROGENPLATFORM BLOCKCHAIN CHANGING FINTECH APPROACH

### ISSUE THREAD

**Issue by olisa4** [HydroBlockchain/hcdp#84]
**Link to the posted content**
https://steemit.com/bitcoin/@olisexxy/hydrogen-platform-blockchain-changing-the-fintech-approach 
**Ethereum Address**
0xC2933176a9be2116721A2681e042111Ad22F8266

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
