### ISSUE TITLE
10 Reasons why Hydrogen platform (hydro) coin can be the greatest coin in future

### ISSUE THREAD

**Issue by Emmaani** [HydroBlockchain/hcdp#85]
<b>Link to the posted content</b>

https://medium.com/@aniemmanuel/reasons-why-hydrogen-platform-can-be-one-of-the-greatest-coin-in-future-576cb8403680
<b>Ethereum Address</b>
<font color="green">
0x0C9F3E6A9d446215BF5D62eD88A21925Ce628F52</font>

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
