### ISSUE TITLE
SDK & Code Libraries

### ISSUE THREAD

**Issue by ealtaca** [HydroBlockchain/hcdp#9]
**What language is it in?**
Java

**Describe how to use it**
I have mentioned with all detail in README.md file

**Any important links?**
https://github.com/ealtaca/raindrop-sdk

**Ethereum Address**
0xbaf3d47e049cbb3a8f2718830beebc334be613c9

**Other important information**

**Comment by ghost** [comment]
This looks like a promising start @ealtaca. However, we'll be updating our API very soon, which will require changes to this SDK. We will ping you once these changes are live, and if you are interested in maintaining/updating your codebase then we can discuss further at that point.

**Comment by ghost** [comment]
Closed per #209
