### ISSUE TITLE
HYDROGEN RAINDROP (YAĞMUR DAMLASI)

### ISSUE THREAD

**Issue by myyigit** [HydroBlockchain/hcdp#95]
https://steemit.com/hydrogen/@myyigit/hydrogen-yagmur-damlasi-raindrop

0x4aCb01c2139A247C10f249FA5B5837C75D5565B3

**Comment by myyigit** [comment]
https://medium.com/@myyigit/hydrogen-ya%C4%9Fmur-damlasi-raindrop-ef62446ecf52

0x4aCb01c2139A247C10f249FA5B5837C75D5565B3

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
