### ISSUE TITLE
Creation of a new digital

### ISSUE THREAD

**Issue by Holyridax** [HydroBlockchain/hcdp#97]
Creation Of a New Digital Economy - HYDROGEN

May 17, 2018 • 9 Likes • 7 Comments
According to research conducted by a global cybersecurity and risk mitigation company (NCC Group), the number of security vulnerabilities detected in the financial services sector has increased by over 418% in the last 4years.

They examined the vulnerabilities found in 168 financial services organizations, and the result revealed that the number of security vulnerabilities detected within the financial services sector has grown exponentially in recent years, soaring from an average of 217 in 2013 to 910 in 2016, per organization. Web application framework vulnerabilities constituted about 24.7% of the issues captured as being medium to high risks, and this emanates from within the software designed to aid the evolution of web applications including web APIs, services and resources. This number had increased almost five-fold since 2013.

In its bid to better engage with customers, the financial services sector seems to be progressively taking a digital-first perspective. However, the resultant effect of this approach is that organizations will further be exposed to a growing number of security vulnerabilities. Also, data privacy and protection is key as customers would only want to have a relationship with financial services they can trust.

However, with the utilization of Blockchain technology, Hydrogen aims to create a digital ecosystem for a better, easier, secure, more open and inexpensive financial products, thus bringing fintech to the masses. The hydrogen platform will allow new and existing private systems to easily integrate and leverage the unchangeable & clear dynamics of a public blockchain to intensify application, document security, identity management, transactions, and artificial intelligence. With the use of Hydrogen's modular set of global REST APIs, the high cost and time associated with building and running digital financial services applications will be eliminated.

The hydrogen platform has three working products (REST APIs) namely: The Hydrogen atom, Hydro blockchain, and Hydrogen ion.

- The hydrogen ion was designed to help build highly developed fintech products from one API platform within minutes.

- The hydro will enable private financial systems to easily leverage on public blockchain

- With the use of machine learning, the Hydrogen ion will allow data scientist to pre-process data sets and assess models.

THE HYDRO PROJECT

The very first phase of the hydrogen project is the ‘Hydro Raindrop’. In this phase, developers and enterprises will be able to integrate any API with the hydrogen REST API on the hydrogen platform through the Hydro Raindrop. The Hydro raindrop is a blockchain-based authentication service built on the hydro public ledger and will be made available in the form of an open source software, in order to provide extra security for sensitive financial data that might be vulnerable to hacks.

In as much as traditional SMS and email 2FA provides some form of security, they still have security issues and are also the minutest secure recourse for 2FA (two-factor authentication). They provide the least secured option because, OTP messages can be compromised in many ways ranging from sim swaps, phishing emails, malware download, to attacks against GSM and 3G networks. However, with the advent of the hydrogen raindrop 2FA, private systems will be strengthened with a blockchain-based authentication layer, and user access functions such as payments, sign on, account creation etc., will be protected with the use of public key cryptography.

The raindrop authentication services come in two forms; client and system side. The client-side aims to protect the end user, whilst the system side is for the security of large private systems, APIs and databases. Platforms who intend to enhance their security protocols with the use of the hydro raindrop 2FA (either client or system side), will have to integrate the raindrop API into their systems, and this integration is usually completed within some few hours. For example, if a platform decides to integrate with the client-side raindrop, users of the platform would have to download the hydro mobile app which is available on IOS and Google play stores upon completion of the integration. The hydro app is a blockchain-based 2FA decentralized app built to provide supplemental security for the end users.

Key Distinctive features of the hydro raindrop 2FA include:

-   User identity security through the hydro blockchain

-   Alert notifications upon login attempts

-   Easy seed recovery upon a change of device

-   Highly cost-effective, as it is free for both the platform and users.

The hydrogen raindrop focuses on the rudimentary application difficulties associated with user authentication. However, issues related to a user identification, verification and privacy will be addressed in the hydrogen snowflake, which is the phase 2 of the hydrogen project. Upon the successful implementation and launch of the snowflake, users will have the capability to store and handle unique digital fingerprints.

The other phases include the Ice, Tide, and Mist phase respectively, each with its own specific function and will be implemented subsequently.

**Comment by Holyridax** [comment]
0x86E0924CBfCCbf2AC2E061DB2884a5E2f33Dcf89

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
