### ISSUE TITLE
Hydro changing history

### ISSUE THREAD

**Issue by Holyridax** [HydroBlockchain/hcdp#98]
Hydro, changing history 

Hydro is a new innovation that presents programmers the opportunity to grow their abilities to creating life transforming application . 
This millenium has witnessed the growth of information tecnology like never before . 
There is a great population who are creating a unique outlook to their environment.Giving rise to an influx of life benefitting applications on smartphones.From social to educational ,informative and financial .
Therefore Hydro is making a landslide contributions into the growth of programming and application development with its various projects .
Hence , the project hydro is a great project to invest in . 
Hydro has a great team with great knowledge .

**Comment by Holyridax** [comment]
0x86E0924CBfCCbf2AC2E061DB2884a5E2f33Dcf89

**Comment by ghost** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
